### ISSUE TITLE
Adding a positional argument with `.unconditionalRemaining` strategy disables the help flag

### ISSUE THREAD

**Issue by pvieito** [apple/swift-argument-parser#100]
Adding a positional argument with `.unconditionalRemaining` strategy disables the help flag.

**ArgumentParser version:** `0.0.4` and `master` branch.
**Swift version:** Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Examples

- Example 1:

```swift
struct ExampleTool: ParsableCommand {
    @Argument(parsing: .unconditionalRemaining)
    var processArguments: [String]
    
    func run() throws {
        print(self.processArguments)
    }
}

ExampleTool.main()
```

```bash
$ example-tool --help
["--help"]
```

- Example 2:

```swift
struct ExampleTool: ParsableCommand {
    static var configuration: CommandConfiguration {
        return CommandConfiguration(helpNames: .customLong("x-help"))
    }

    @Argument(parsing: .unconditionalRemaining)
    var processArguments: [String]
    
    func run() throws {
        print(self.processArguments)
    }
}

ExampleTool.main()
```

```bash
$ example-tool --x-help
["--x-help"]
```

### Expected behavior
It should show the command help.

**Comment by natecook1000** [comment]
This is the intended behavior for `.unconditionalRemaining` — otherwise there would be no way to capture a `--help` flag provided by the user. We should expand that case's documentation to indicate that only explicitly defined options/flags are captured by the argument, however.

If you need a workaround, you can declare your own help flag (it has a bit of a wonky interaction with the `--help` in the help text, which is a separate issue):

```swift
struct ExampleTool: ParsableCommand {
    @Flag(name: .shortAndLong, help: .hidden)
    var help: Bool

    @Argument(parsing: .unconditionalRemaining)
    var processArguments: [String]

    func validate() throws {
        if help {
            throw CleanExit.helpRequest()
        }
    }

    func run() throws {
        print(self.processArguments)
    }
}

ExampleTool.main()
```
```
$ example-tool --x-help
["--x-help"]
```

**Comment by pvieito** [comment]
Oh, ok! Yes, it shows one `--help` flag that *does not work*:

```swift
struct ExampleTool: ParsableCommand {
    @Flag(name: .shortAndLong, help: .hidden)
    var help: Bool

    @Argument(parsing: .unconditionalRemaining)
    var processArguments: [String]

    func validate() throws {
        if help {
            throw CleanExit.helpRequest()
        }
    }

    func run() throws {
        print(self.processArguments)
    }
}

ExampleTool.main()
```

```
$ example-tool --x-help
USAGE: example-tool

ARGUMENTS:
  <process-arguments>

OPTIONS:
  -h, --help              Show help information.
```
