### ISSUE TITLE
`validate()` is not called on parent commands even though their arguments are required

### ISSUE THREAD

**Issue by kennyyork** [apple/swift-argument-parser#103]
When a subcommand is parsed and executed, its parent command arguments are parsed but `validate()` is never called.  It seems odd that the arguments are required for the command to be accepted, but are not validated.  

**ArgumentParser version:** `master`
**Swift version:** Apple Swift version 5.2

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
```
private struct BaseCommand: ParsableCommand {
  static var configuration = CommandConfiguration(
    commandName: "base",
    subcommands: [SubCommand.self]
  )

  @Option()
  var baseFlag: String

  mutating func validate() throws {
    throw HelpRequested
  }
}

extension BaseCommand {
  struct SubCommand : ParsableCommand {
    static var configuration = CommandConfiguration(commandName: "sub")

    @Flag()
    var subFlag: Bool

    mutating func validate() throws {
      print("Validated SubCommand")
    }
  }
}
```

### Expected behavior
Because `--base-flag` is required for the command to run, I would expect at the least that `BaseCommand.validate()` be called. 

### Actual behavior
`BaseCommand.validate()` is never called when invoking SubCommand

**Comment by natecook1000** [comment]
Fixed by #104! Thanks @kennyyork!
