### ISSUE TITLE
Add a new property wrapper type to make it easier to add non-argument properties to ParseableArguments

### ISSUE THREAD

**Issue by kennyyork** [apple/swift-argument-parser#105]
Its slightly annoying to add properties to a ParsableArgument that are not arguments.  For example:

```
struct Command : ParsableCommand {
    var someValue: String
   
    @Flag()
    var myFlag: Bool

    private enum CodingKeys: CodingKey {
      case myFlag
    }
  }
```

A use case I have for this is that I would like to have the `validate()` command create some objects or setup some state and store it on the Command object, but doing so requires adding the `CodingKeys` enum.

Would it make sense to add something like `@Ignored` or `@Excluded` that conform to `Decodable` to make it so that `CodingKeys` does not have to be declared?

**Comment by natecook1000** [comment]
This was resolved by #268, which handles unwrapped variable properties like `someValue` automatically.
