### ISSUE TITLE
Add a default value for @Option when the type is an Array

### ISSUE THREAD

**Issue by fdiaz** [apple/swift-argument-parser#107]
There's currently no way that I've found to have a default option when an `@Option` is an array

```swift
@Option(parsing: .upToNextOption)
var foo: [String]
```

I'd like to do something like:

```swift
@Option(default: ["someValue"], parsing: .upToNextOption)
var foo: [String]
```

So even if this option is not set, we still get this information.

**Comment by natecook1000** [comment]
@fdiaz Would you expect the default values to be included when the user specifies inputs, or would they be overridden if there's even one value given?

**Comment by fdiaz** [comment]
My thinking was that they would be indeed overwritten.
