### ISSUE TITLE
This project could benefit from a CI / CD setup

### ISSUE THREAD

**Issue by KyleLeneau** [apple/swift-argument-parser#11]
I am thinking that Github Actions would be a good fit for this project to use CI and CD for PR validation, any objections?

**Comment by natecook1000** [comment]
Agreed, Kyle! We're working on getting PR CI testing in place.

**Comment by natecook1000** [comment]
We have PR in testing place now using the Swift CI infrastructure, thanks to @shahmishal! PRs now will need to pass CI on macOS with the latest Xcode and Linux with Swift with the latest versions of 5.1 and 5.2. Available commands are:

- `@swift-ci Please test` (tests all platforms)
- `@swift-ci Please test macOS platform`
- `@swift-ci Please test Linux platform`
