### ISSUE TITLE
Show an error for option and flag name collisions

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#112]
It's possible to define `ParsableCommand` and `ParsableArguments` type with colliding option and/or flag names. This should be an error that's surfaced by a `ParsableArgumentsValidator` type. For example, running this program should fail:

```swift
struct TwoOfTheSameName: ParsableCommand {
    @Option()
    var foo: String
    
    @Option(name: .customLong("foo"))
    var notActuallyFoo: String
}

TwoOfTheSameName.main()
```

Note that each option and flag can have more than one name. We'll eventually need to validate this same problem through the command hierarchy, but validating individual commands is a good first step.

**Comment by iainsmith** [comment]
Looks like this can be closed now 😄
