### ISSUE TITLE
Add a way to skip calling `validate` for testing/other scenarios

### ISSUE THREAD

**Issue by iainsmith** [apple/swift-argument-parser#120]
Hi All. 

I think we can make it easier to write unit tests for ParsableArgument conforming types.

Over the weekend I ported [swift-docker](https://github.com/iainsmith/swift-docker) to use ArgumentParser 0.0.5. I've used computed properties on my `ParsableArguments` options as these are shared by many commands. To write unit tests that didn't trigger the filesystem validation methods. I needed to add a hidden `skipValidation: Bool` flag to the options. See the example below.

I think we could avoid this by providing a public `parseWithoutValidation() -> ParsableArguments` method that skips the call `public func validate() throws`. What do people think. Is this something the library should provide out of the box (even if just for testing)?

## Update

When implementing this in #122 I updated the `parse` and `parseAsRoot` methods to take an optional `skipCustomValidation: Bool = false` parameter.
 
---

## Minimal example

```swift
public struct CLIOptions: ParsableArguments {
  @Option(name: .shortAndLong, default: "latest", help: "swift tag found at https://hub.docker.com/_/swift \n  e.g latest, 5.2, 5.2.2-slim")
  var swift: String

  @Option()
  var image: String?

  @Flag(name: .customLong("skip-validation"), help: .hidden)
  var skipValidation: Bool

  var baseImage: DockerTag {
    DockerTag(version: swift, image: image)!
  }

  public func validate() throws {
    if skipValidation { return }
    // Some validation logic here that might depend on the current 
    // working directory / permissions / networking etc.
  }
}

extension CLIOptions {
  static func parseWithoutValidation(_ args: [String]? = nil) throws -> CLIOptions {
    let fullArgs = args ?? []
    return try parse(fullArgs + ["--skip-validation"])
  }
}

class CLIOptionTests: XCTestCase {
  func testDefaultDockerTag() throws {
    let options = try CLIOptions.parseWithoutValidation()
    XCTAssertEqual(options.baseImage, DockerTag.officialSwiftVersion("latest"))
  }
}

```

**Comment by kylemacomber** [comment]
Isn't this a general issue that is traditionally addressed by mocking or dependency injection? Why do you think the right approach is to bake this into the library?

**Comment by iainsmith** [comment]
So to use a real example, the tests from the project I'm working on are [here](https://github.com/iainsmith/swift-docker/blob/master/Tests/SwiftDockerLibTests/CLIOptionTests.swift) and the `validate` function is [here](https://github.com/iainsmith/swift-docker/blob/f77e36130ce3002c42ad7374158690c701dced03/Sources/SwiftDockerLib/CLIOptions.swift#L39).

The `validate` method checks

* Did you specify multiple exclusive options
* Does the directory have a valid Package.swift file
* Are you running from Xcode (by looking for DerivedData) in the path.

**Rephrasing slightly**
> Can this be addressed by mocking?

CLIOptions is a struct so I can't subclass it and I can't dynamically replace the validate method (until we get something like [dynamic method replacement](https://forums.swift.org/t/dynamic-method-replacement/16619)). If I'd written this in python - I'd just stub out the validate method.

I can mock the environment by creating a temporary directory and files, which I do in the methods that test the validation. e.g `testDirectoryMustContainAPackageSwiftFile`

But I didn't want to have to mock out the entire environment to test the computed properties and the defaults.

Alternatively, I considered

* Not using the validate function on the arguments and running the validation in the command
* Using the --skip-validation flag
* Mappings my ParsableArguments conforming struct into a struct after validating that would contain the computed properties.

These all seemed like bad options, but --skip-validation seemed to provide the least compromise.

---
> Can this be addressed by dependency injection?

Not that I'm aware of, but if so I'd be keen to hear how.
---
> Why do you think the right approach is to bake this into the library?

I think having a great testing story is a valuable feature.

Having a simple way to write unit tests that skip `validate` would be useful to me and I suspect others.  I think any command line tool that handles external resources such as the filesystem & Network is going to run into this fairly frequently and I think the `--skip-validation` hidden flag (or some other pattern) would become fairly common.

:shrug: - on the other hand there is a fairly trivial workaround available.

**Comment by natecook1000** [comment]
For this kind of testing, I think the right approach is to create a memberwise initializer for your type rather than to use the parsing machinery. If you’re directly creating an instance of your type, then you can test any of its computed properties or methods without calling `validate()`.

The `parse` -> `validate` -> `run` pipeline is a contract that the library provides to its clients. Having a flag to skip the validation step adds a path for introducing bugs as much as it might ease creating test cases.

Thanks for bringing up this issue! Testing is an important part of the CLI tool development process, and it’s great to hear what you’ve run into while using the library. Feel free to re-open the issue if you’d like to discuss further.

**Comment by iainsmith** [comment]
Thanks @natecook1000 & @kylemacomber - Direct initialisation would be ideal. I tried this in an earlier iteration and hit the `directlyInitializedError`, I think because I was trying to add non codable types with a default value & was forgetting you can exclude properties in the CodingKeys enum.

The current error copy, indicates that it's incorrect to initialise a ParsableArguments or ParsableCommand directly.

```swift
internal let directlyInitializedError = """
  --------------------------------------------------------------------
  Can't read a value from a parsable argument definition.

  This error indicates that a `ParsableCommand` or `ParsableArguments`
  type is being initialized directly, instead of by calling `parse`,
  `parseAsRoot`, or `main`. See the documentation for correct usage.
  --------------------------------------------------------------------
  """
```

It might be helpful to update that error specifically to clarify when direct initialisation is/isn't supported, as it was definitely part of what lead me down this track. I think ideally it could suggest solutions to the likely cause. I took a quick scan of the docs and couldn't see any helpful clarification that exists today (but it was a quick skim)

Thanks for the support. I'm hugely enjoying being able to use and engage with open source projects from apple.

**Comment by natecook1000** [comment]
That's a great point! I forgot about the wording of that error in my post above 🤦  — it should be more clear about the different ways of getting here. In addition, something about providing a memberwise initializer would be a good addition to the [guide on manual testing](https://github.com/apple/swift-argument-parser/blob/master/Documentation/06%20Manual%20Parsing%20and%20Testing.md).
