### ISSUE TITLE
Is it possible to build interactive CLI Tools based on ArgumentParser?

### ISSUE THREAD

**Issue by vidugloeck** [apple/swift-argument-parser#125]
I'd like to build an interactive CLI, but wasn't able to setup ArgumentParser in a way that I could prompt the user after a command is run. Is that feature not supported (yet) or am I missing something?

**Comment by natecook1000** [comment]
ArgumentParser doesn't provide any support for interactive CLI tools. The Swift standard library includes the `readLine()` function, which you can use to build a rudimentary prompt-based tool, but for anything more sophisticated you'd need to build or add what you need as a dependency.

Thanks for your interest — please feel free to discuss this question more on the forums! 

https://forums.swift.org/c/related-projects/argumentparser/60
