### ISSUE TITLE
Different mechanisms for conforming to ExpressibleByArgument

### ISSUE THREAD

**Issue by mergesort** [apple/swift-argument-parser#127]
I'm using Argument Parser to build an internal tool, so the names below are a bit obscured but practically one of the use cases is for updating debug keys and values.

My desired syntax for running my app is something akin to `swift internalTool update key value`, where the key and value are positional arguments.

It currently works if I use a `[String]` for the `@Argument` like so:
```
@Argument(help: "The key and value you wish to update")
var keyAndValue: [String]
```
The downside of this is manually parsing the first and second parameters in the `run` function of my subcommand, which isn't a safe procedure.

I think a cleaner syntax would be something like this:
```
@Argument(help: "The key and value you wish to update")
var keyAndValue: KeyValuePair
```
I'm not necessarily proposing creating a `KeyValuePair` type, but to extend `ExpressibleByArgument` to have an alternative initializer that allows for a `[String]` to be used instead of a `String`.

With the status quo I would have used something like this to create my construct:
```
struct KeyValuePair: ExpressibleByArgument {
    let first: String
    let second: String
    init?(argument: String) {
        print(argument)
        self.first = // parse the string for the first argument
        self.second = // parse the string for the second argument
    }
}
```

But that would require me to run the command as `swift internalTool update "key value"` instead of `swift internalTool update key value`, which is a cleaner variant.

Happy to provide any help as needed, thanks for the fantastic library!

**Comment by kylemacomber** [comment]
I take it you don't want to do something like:

```
@Argument(help: "The key you wish to update")
var key: String

@Argument(help: "The value you wish to update")
var value: String
```

**Comment by mergesort** [comment]
I would be completely fine with that syntax, though it doesn't appear to work right now. I tried out what you proposed and it works, but in my tests it doesn't actually take into account positions:

I flipped the order of the variables in my Swift file as such:
```
@Argument(help: "The feature switch you wish to update in Twitter")
var value: String

@Argument(help: "The feature switch you wish to update in Twitter")
var key: String
```

And then ran `swift internalTool update value key` (rather than `swift internalTool update key value` to see if it would work, and it didn't because the order of the `key` and `value` was still first and second, rather than second and first.

Is that what you mean @kylemacomber or did I misunderstand the intention of your suggestion?

**Comment by kylemacomber** [comment]
> in my tests it doesn't actually take into account positions

So @natecook1000 would be able to speak to the implementation, but I'm under the impression that order of arguments are taking into account. At least that seems to be the case for this super simple test.

Code:
```swift
import ArgumentParser

struct InternalTool: ParsableCommand {
    @Argument()
    var key: String

    @Argument()
    var value: String

    func run() {
        print("key:", key, "value:", value)
    }
}

InternalTool.main()
```

Output:
```
$ swift run InternalTool
Error: Missing expected argument '<key>'
Usage: internal-tool <key> <value>

$ swift run InternalTool first second
key: first value: second
```

Code:
```swift
import ArgumentParser

struct InternalTool: ParsableCommand {
    @Argument()
    var value: String

    @Argument()
    var key: String

    func run() {
        print("key:", key, "value:", value)
    }
}

InternalTool.main()
```

Output:
```
$ swift run InternalTool
Error: Missing expected argument '<value>'
Usage: internal-tool <value> <key>

$ swift run InternalTool first second
key: second value: first
```

**Comment by mergesort** [comment]
Once again proving that the two hardest problems in computer science are caching and getting a human to do the right thing, I was running a cached version of built product when testing, and so of course my changes weren't properly reflected.

This works great, I'm more than happy to have this as a solution for my problem. I didn't come across any documentation about the positional nature of the arguments, so I'm going to add it to our internal tool as comments, but is there anywhere it's documented that I can link to as well?

Thanks so much @kylemacomber!

**Comment by natecook1000** [comment]
That idea should be covered in the document below, but we don’t have an example showing multiple `@Argument` properties, only an array. Definitely an improvement to make there!

https://github.com/apple/swift-argument-parser/blob/master/Documentation/02%20Arguments%2C%20Options%2C%20and%20Flags.md

**Comment by mergesort** [comment]
Awesome! I had seen the array example so I'm glad I didn't just overlook something, but appreciate a link to the documentation. Will close out the ticket, thanks again everybody. 😄
