### ISSUE TITLE
Request  Custom Short STRING arguments (not just Character) for ArgumentParser

### ISSUE THREAD

**Issue by richiwalt** [apple/swift-argument-parser#131]
There are several cases where double char values (i.e. a STRING) are useful as SHORT Options, I’ll give just one example:

Common in the world of HPC (High Performance Computing) is the qsub command to submit jobs to run on a supercomputer.  (Government, Industry, and Research HPC sites do this all the time) 

Common short flags for a qsub are:
-a for account, or, as we name it: projectID
-w for walltime holding HH:MM:SS string for the time requested to allow a job to run
-**nn** for number of backend compute nodes
-**np** for number of processes per node to run
-q for desired queue to run in 

I would love to have both short and long arguments available to me in Swift ArgumentParser (long arguments would be good for newbies entering HPC jobs, short values are what everyone uses in the long run) ... but there is no other good short names for number of nodes than -**nn**, likewise -**np** is common in this field for number of proc or nprocs ( we don’t even say out loud “number of processes per node” we say “nprocs” ).  

Please consider allowing a TWO-CHARACTER (or more) custom way to have SHORT VALUE TYPE ARGUMENTS.

I tried:  .customShort( “nn”) and was scolded that “nn” is not a Character.  I do understand the -vvvv argument that is is four singles ... etc ... but not every case needs that strict unbendable convention.  

——— my coding example follows ——-

I am working on translating my python qsub script to Swift qsub script.  A supercomputer can have many different backend compute nodes, and HPC resources are allocated to users by a job scheduler.  We are using the PBS job scheduler ... a qsub command looks like:

Prompt> qsub -A ProjectID -l walltime=HH:MM:SS -l select-{nNodes}:ncpus={fixedHardwareNumberofCPUPerNode}:mpiprocs{userDesiredNumberOfProcessesPerNode}{:optionalPBSNodeFlagString=keyNumber} -q {queueToRunJob}  {optional -I flag for interactive job}

It’s a pretty long command, and it is used all the time in the world of HPC. 

My utility program prints all available qsub job types that are available for the given supercomper where the script is executing.

It prints, for example,

<pre>
Athena standard qsub:
   qsub -A {-p ProjectID} -l walltime={-w HH:MM:SS} -l select={-nn nNodes}:ncpus=32:mpiprocs={-np nProcs} -q {-q queue} -I

Athena large qsub
   qsub -A {-p ProjectID} -l walltime={-w HH:MM:SS} -l select={-nn nNodes}:ncpus=32:mpiprocs={-np nProcs}:bigmem=1  -q {-q queue}. -I 

Athena gpu qsub
    qsub -A {-p ProjectID} -l walltime={-w HH:MM:SS} -l select={-nn nNodes}:ncpus=32:mpiprocs={-np nProcs}:ngpus=1 -q {-q queue} -I  

</pre>

The user is able to replace all values in the {} above (which is just a default string, including the braces) with the flags printed inside of the braces. 

For example, executing:
<pre>
Prompt>show_qsub_commands -a MYPROJECTID -w 00:10:00 -nn 4 -np 16 -q debug 
</pre>

Causes the output to print as follows:

<pre>
Athena standard qsub:
    qsub -A MYPROJECTID -l walltime=00:10:00 -l select=4:ncpus=32:mpiprocs=16 -q debug -I

Athena large qsub
   qsub -A MYPROJECTID -l walltime=00:10:00 -l select=4:ncpus=32:mpiprocs=16:bigmem=1 -q debug -I

Athena gpu qsub
  qsub -A MYPROJECTID -l walltime=00:10:00 -l select=4:ncpus=32:mpiprocs=16:ngpus=1 -q debug -I 

</pre>

**Comment by natecook1000** [comment]
Hello @richiwalt — thanks for the issue report! You can define "long" names that use a single dash by writing `@Option(name: .customLong("nn", withSingleDash: true))`. Does that help with your use case?

The distinction between long and short names in this case is that only short names can be combined into a "pack", like `-awq`. Being able to combine multi-character short names in this way could end up being confusing for end users (and be more likely to introduce ambiguities).

**Comment by richiwalt** [comment]
Thanks @natecook1000 !  Your suggestion is what I wound up doing even before you suggested it.   

I would still like the option of using .customShort(withString: "np") ... and perhaps a note in the documentation saying this is discouraged for -awq cases where this could be confusing.  Then a note consider using .customLong("np", withShortDash: true) as you suggested. 

But, using the .customLong() clobbers the fully spelled out -num-processes-per-node for newbies entering qsub commands for the first time.  

I understand the reasoning ... but, in this case, **I prefer Python's argument parser usage **, where short is always given with a singe dash,  followed by one or more characters, and long is always given by double dashes, followed by one or more characters in it's string.  The parser "knows", based on what is added, whether or not "-np" is a single argument, or two short arguments.  (Swift should be better than python.) 

```python
#! /usr/bin/python
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('-q',  '--queue',    metavar='queue',    required=False, default='{-q queueName}')
parser.add_argument('-w',  '--walltime', metavar='walltime', required=False, default='{-w HH:MM:SS}')
parser.add_argument('-nn', '--nNodes',    metavar='nNodes',   required=False, default='{-nn desired_nodes}')
parser.add_argument('-np', '--nProcs',    metavar='nProcs',   required=False, default='{-np procs_per_node}')
parser.add_argument('-sq', '--show_queues', required=False, action='store_true', default=False)

parsed_args = parser.parse_args()

show_queues_flag = parsed_args.show_queues
queue_name = parsed_args.queue
nnodes     = parsed_args.nNodes
nprocs     = parsed_args.nProcs
walltime   = parsed_args.walltime
```

**Comment by natecook1000** [comment]
Note that you aren't limited to only a single long or short name for an option — you can specify that both a custom long name and the standard long name are usable, or two custom long names and a short name, etc.

```swift
@Option(name: [.long, .customLong("np", withSingleDash: true)], ...)
var numProcessesPerNode: Int
```
