### ISSUE TITLE
Short name arguments don't accept an equal sign between key/value pairs

### ISSUE THREAD

**Issue by captainbarbosa** [apple/swift-argument-parser#132]
**ArgumentParser version:** `0.0.5`, `master`
**Swift version:** 

```
Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0
```

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

Defining an option with a `.customShort` name doesn't support an equal sign (`=`) between key-value pairs.

### Expected behavior
Specifying an option with an equal sign in between key-value pairs should succeed, as noted in the [documentation](https://github.com/apple/swift-argument-parser/blob/master/Documentation/02%20Arguments%2C%20Options%2C%20and%20Flags.md#declaring-arguments-options-and-flags):

>Options are named key-value pairs. Keys start with one or two dashes (- or --), and a user can separate the key and value with an equal sign (=) or a space.

### Actual behavior

The command line execution fails when `cool -r=4` is attempted:

```
Error: Unknown option '-r'
Usage: cool [--repeat-count <repeat-count>]
```

Here is a sample `main.swift` you can use to reproduce:

```swift
import Foundation
import ArgumentParser

struct BeCool: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "cool",
        abstract: "Be super cool",
        discussion: "Demonstrates how to be cool",
        version: "0.0.1",
        shouldDisplay: true)
    
    
    /** OPTIONS */
    // [FAIL]  -r=4
    // [OK]    -r 4
    // [OK]    --repeat-count=4
    @Option(
        name: [.customShort("r"), .long],
        help: "Number of times the word \"Cool\" is repeated. Defaults to 1."
    )
    var repeatCount: Int?
    
    func run() throws {
        
        let outputString = String(repeating: "Cool ", count: repeatCount ?? 1)
        
        print(outputString)
    }
}

BeCool.main()
```

**Comment by friedbunny** [comment]
Completely uninformed drive-by, but [`SplitArguments.swift`](https://github.com/apple/swift-argument-parser/blob/c23dfb26daff914b2111d21389a6282adc2b9231/Sources/ArgumentParser/Parsing/SplitArguments.swift) looks like a good place to begin tromping around.

**Comment by natecook1000** [comment]
Thanks so much for the report, @captainbarbosa!

A couple extra notes:

- This also doesn't work for options with the default `.short` or `.shortAndLong` name
- We'll want to disallow this kind of joining when short options are grouped, like `-rc=5` — only single short options should allow this

**Comment by BenLeggiero** [comment]
Cool Cool
