### ISSUE TITLE
Allow specification of the value name to use for an option

### ISSUE THREAD

**Issue by armandgrillet** [apple/swift-argument-parser#137]
I have this option:
```
@Option(name: [.short], help: "Only search for files with a specific pattern")
var filenamesPattern: String
```

This results in this help:
```
OPTIONS:
  -f <f>                  Only search for files with a specific pattern
```

I would like to print `-f <pattern>` instead of `-f <f>` to make the help more descriptive. I have looked at the `NameSpecification` in swift-argument-parser but couldn't find a way to specify what the value should be (in my example: `pattern`). 

Note that `pattern` would also not be the name of the variable relating to this option.

**Comment by natecook1000** [comment]
Hi @armandgrillet! The library supports this as a property of the `ArgumentHelp` type. In your case, you’d write it like this:

```swift
@Option(
    name: .short, 
    help: ArgumentHelp(
        "Only search for files with a specific pattern",
        valueName: “pattern”))
var filenamesPattern: String
```

If the argument help definition gets too bulky, I sometimes move them to elsewhere in the file.

**Comment by armandgrillet** [comment]
Oh sorry, I didn't know about `ArgumentHelp`. Thanks for the code snippet, the output is exactly what I wanted to print.

**Comment by armandgrillet** [comment]
Now I see that this is explained in [Customizing Help](https://github.com/apple/swift-argument-parser/blob/3166c458f99e51892aab0675ec2d1efb373864ed/Documentation/04%20Customizing%20Help.md) 📖.

I wrote the issue after reading [this part of the documentation](https://github.com/apple/swift-argument-parser/blob/3166c458f99e51892aab0675ec2d1efb373864ed/Documentation/02%20Arguments%2C%20Options%2C%20and%20Flags.md#customizing-option-and-flag-names) and I wonder if adding a line there could be useful 🤔.The value name is only used in the help but, due to the fact that it is placed right next to the flag descriptions, it still seems related to the `Option` documentation.
