### ISSUE TITLE
Proposal: Allow passing of global arguments/options/flags

### ISSUE THREAD

**Issue by bdrelling** [apple/swift-argument-parser#144]
In addition to using flags like `--help`, I'd really love to have a flag like `--verbose` that exists in every one of my commands or subcommands without being defined over and over.

Currently, I could probably subclass `ParsableCommand` into something like `VerboseParsableCommand`, but I'm wondering if there would be a simpler way to have flags cascade downwards, specifically with regards to showcasing it in the help documentation.

If I have a command `format` with subcommands `autocorrect` and `analyze`, it would be nice if I could specify `--verbose` only within the `format` command and have it still cascade down to `autocorrect` and `analyze` without having to add it into each option every time.

**Comment by natecook1000** [comment]
While it’s not automatic in the way you’re asking, the way to do this is to define a `ParsableArguments` type with your global options and include it in every subcommand with the `@OptionGroup` property wrapper.

```swift
struct GlobalOptions: ParsableArguments {
    @Flag() var verbose: Bool
}

struct Format: ParsableCommand {
    static let configuration = 
        CommandConfiguration(subcommands: [Autocorrect.self, Analyze.self])

    struct Autocorrect: ParsableCommand {
        @OptionGroup() var globalOptions: GlobalOptions
        // ...
    }

    struct Analyze: ParsableCommand {
        @OptionGroup() var globalOptions: GlobalOptions
        // ...
    }
}
```

The problem with trying to make it automatic is that it isn’t clear about how to access the parsed value. How would `Autocorrect` access `verbose` value if it’s only defined on `Format`?

**Comment by bdrelling** [comment]
Oh wow, that's even better than I was looking for because it's opt-in per-command. I have no idea how I didn't discover this while hunting around in the library last night. Thanks for taking the time to share this! I'll go ahead and close the issue.
