### ISSUE TITLE
Strongly typed negative integers interpreted as flags unless `=` used

### ISSUE THREAD

**Issue by erica** [apple/swift-argument-parser#153]
![Screen Shot 2020-05-18 at 2 57 25 PM](https://user-images.githubusercontent.com/32688/82259079-3bd06780-9918-11ea-884d-32505381bcaa.png)

```
% greet --points 10
Hello, World!!!!!!!!!!
% greet --points -10
Error: Missing value for '--points <points>'
Usage: greet [--points <points>] [--name <name> ...] [--single] [--double] [<greeting> ...]
% greet --points=-10
Error: Exclamation count must be positive
% 
```

The correct behavior is the error. There are times passing negative numbers is the desired outcome

**Comment by alexito4** [comment]
This seems related to #31. I raised that a while ago but haven't keep up with the latest changes. FWIW there is a workaround in a comment.

**Comment by natecook1000** [comment]
Thanks, @erica! We can track this issue with #31.
