### ISSUE TITLE
Option with default value being treated as required argument

### ISSUE THREAD

**Issue by tesch** [apple/swift-argument-parser#171]
When initializing a custom option with a default value of a type that is different from the type of the actual option property, it is actually treated as a required argument.

```swift
enum Flag {

    case left, right

    init(_ value: String?) {
        self = (value == nil) ? .left : .right
    }

}

@Option(default: nil, transform: Flag.init)
var flag: Flag
```

In `--help` this option is presented as `--flag <flag>` instead of `[--flag <flag>]` and it is impossible to run without given and explicit argument to `--flag`. The default value is effectively ignored.

**Comment by natecook1000** [comment]
This is the expected behavior when you use a `nil` default value for a non-optional property — if the default is `nil`, the user needs to provide a valid value so that the `flag` property can have a value.

To resolve this, you can change the declaration to this:

```swift
@Option(transform: Flag.init) var flag: Flag?
```

**Comment by tesch** [comment]
OK, what about this:

```swift
@Option() var a: String?

@Option(transform: URL.init(fileURLWithPath:)) var b: URL?
```

Both `a` and `b` are optional, it is possible to run without specifying any of them. In `--help` they are presented as `[--a <a>] --b <b>` though, which to my eye looks as if only `a` should be optional. Is this correct behavior as well?

**Comment by natecook1000** [comment]
That's incorrect behavior, but happily has been fixed since the last release. I'm hoping to release 0.1.0 this week, which will include that fix.
