### ISSUE TITLE
Target named "TestHelpers" conflict with "swift-se0270-range-set" unit-test target

### ISSUE THREAD

**Issue by dehengxu** [apple/swift-argument-parser#18]
As title mentioned

**Comment by natecook1000** [comment]
Hi @dehengxu — I'm having trouble reproducing this error. Could you say more about what you're trying to do when you run into this?

**Comment by dehengxu** [comment]
> Hi @dehengxu — I'm having trouble reproducing this error. Could you say more about what you're trying to do when you run into this?

I use packages  ArgumentParser and swift-se0270-range-set which both have TestHelpers target
