### ISSUE TITLE
Dictionary as a parameter

### ISSUE THREAD

**Issue by artemnovichkov** [apple/swift-argument-parser#182]
I want to use dictionary as a parameter. Is it possible with current implementation?
```swift
@Option(help: "The output for the template.")
var parameters: [String: String]
```
It's not possible with current implementation as I understood:
```
Referencing initializer 'init(name:default:parsing:help:)' on 'Option' requires that '[String : String]' conform to 'ExpressibleByArgument'
```
Can we add something like:
```
--parameters key1:value1 key2:value2
```

**Comment by natecook1000** [comment]
Hi @artemnovichkov! Collections other than `Array` aren’t supported for options. I’d recommend making that a `[String]` property, and then converting it to the dictionary you need in your `run()` method.

**Comment by artemnovichkov** [comment]
Thanks for the answer! I used an array with custom Parameter object and parse keys and values manually.

**Comment by natecook1000** [comment]
Awesome. I haven’t found an obvious/prevalent way to decode key/value pairs like that, so it seems better left to the individual use case.
