### ISSUE TITLE
Decompose "exit()" and "print()" from implementation

### ISSUE THREAD

**Issue by joetennant** [apple/swift-argument-parser#190]
In some cases, it is desirable to use a command parser without exiting the process and/or redirecting the printing of help messages.

Proposal (Printing)
A `TextOutputStream` would be optionally provided to `main()` or `parseAsRoot()` to handle the output from help. 

Proposal (Handling Exit)
A protocol would be created that would expose an exit handler. An implementation of an exit handler could be provided to `main()` or to `parseAsRoot()` and would be called to actually exit the process (or provide whatever functionality may be desirable).

For example (using a protocol)
```
protocol ExitHandler {
   func exit(exitCode: Int)
}
class CleanupBeforeExit: ExitHandler {
   func exit(exitCode: Int) {
      doSomethingImportant()
      sendSometNotifications()
      cleanUpResources()
      darwinExit(exitCode)
   }
}

**Comment by BenLeggiero** [comment]
I'm sorry; I don't follow. Are you using this outside a shell? Often, I encounter these same desires, but my shells all have built-in ways to [redirect output](https://askubuntu.com/a/625230/587585) and handle different exist statuses.

```sh
someCommand &> ~/Desktop/test.log
someCommandExitStatus=$?

if [ 0 -eq $someCommandExitStatus ]; then
    doSomethingImportant
    sendSomeNotifications
    cleanUpResources
fi
```

If you're talking about maybe some sort of `defer` kinda concept (`finally` in other languages) to close ports and stuff before exiting the process, then I think I can see where you're coming from. That wouldn't have to know about exit codes, though, and shouldn't handle exiting. Perhaps my API design would be like this:

```swift
// In this repo:

public protocol ParsableCommand: ParsableArguments {
  // Same stuff as today:
  static var configuration: CommandConfiguration { get }
  static var _commandName: String { get }
  mutating func run() throws

  // I would add this:

  /// Called immediately after an `exit` call, before the command actually exits.
  ///
  /// Use this to clean up any remaining resources your command was using up. The
  /// same exit code which was used to call `exit` will still be returned from
  /// this command after this function returns.
  func commandWillExit()
}



public extension ParseableCommand {
    func commandWillExit() {} // This makes it optional, doing nothing by default
}



// In your code:

struct MyCommand: ParseableCommand {
  ...

  func commandWillExit() {
    doSomethingImportant()
    sendSomeNotifications()
    cleanUpResources()
  }
}
```

**Comment by joetennant** [comment]
Thanks for the response. I apologize for not adding more detail in the initial request. 

I admit this is an odd request, definitely an edge case. As far as `print()` goes, I personally don't need to change this for my use. However, I do have a bizarre combination of application requirements and macos issues (catalina) that require me to run an `NSApplication` based tool. This tool is primarily launched from other applications, and needs to accept parameters to control how the application behaves.

This library is perfect for parsing those arguments and converting them into a Command which can invoke the functionality I need. But, I need to start and stop my process a bit differently than "normal". In my case, calling `_exit()` is causing some issues with some other frameworks.

It seemed to me that it would be a nice to extract the "process control" part of this tool (which is a very small part of the tool) to make it a bit more generic. In other words, make the primary responsibility of the tool "parsing Arguments into Commands" and decomposing the other bits (`print()` was the only "other bit" I could think of). Of course, 99% of the time, calling `_exit()` is exactly the right thing to do. But, in my case, its not.

There are probably 3 or 4 ways to deal with this, from passing in a delegate or closure, to simply  returning from the command without calling `_exit()`. I am not sure which is the best. In my opinion, the latter might be the easiest and most flexible. Then I can use the tool to "convert arguments into a Command" and be off on my merry way.

My plan is to fork the project and add a small bit of code to handle this weird feature, but I thought I might not be the only one in the world who might find it useful (maybe not... 😄 ). I can submit the change back as a PR and maybe that is helpful.

Thanks for your time!

**Comment by joetennant** [comment]
Btw, I forgot to mention that `commandWillExit()` would probably work really well for what I need.

**Comment by joetennant** [comment]
Now that I dig into the source a bit more -- I think `parseAsRoot()` is all I need. This will avoid "exiting" when the command cannot be parsed, and I can handle printing the usage myself.

**Comment by BenLeggiero** [comment]
Glad you found a solution! And I'm really glad this conversation was opened - I think its ideas might spur future improvements 😄

**Comment by joetennant** [comment]
Yes, using `exit(error)` is pretty close to what I need. It's the help message generation that is the really useful piece of this function. Btw, the documentation _does_ describe my scenario a bit. Using `parseAsRoot()` and `exit(error)` to accomplish just about exactly what I need. 

My biggest hurdle right now is unit testing the commands without invoking `exit()`. The examples actually run the whole process during test, which is a bit more monolithic than I'd like for my purposes. Luckily, I can test all the functionality that the commands invoke separately, and use `parseAsRoot()` as part of the unit tests as well. I am unable to easily validate the help text however. But, this isn't too concerning since I am not attempting to double-test this library.

Thanks again for the response. Sorry if this caused too much churn... 😄
