### ISSUE TITLE
Provide near-miss suggestions

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#2]
If a user mistypes an option, flag, or command, the error message should include a suggestion for the near-miss.

Example:

```
% example --indx 5
Error: Unexpected argument '--indx'
       Did you mean '--index'?
Usage: example [--index <index>] [<values> ...]
```

**Comment by klaaspieter** [comment]
I'll see if I can get this done 👍

**Comment by Sajjon** [comment]
@klaaspieter nice! Hmm @natecook1000 wanna add some more `good first issue` labels (or new issues, with that label)?

**Comment by ahmdyasser** [comment]
Hello @klaaspieter,  how can this be imported to SwiftPM?
