### ISSUE TITLE
Set @Flag globally so my CLI tools network layer can use it

### ISSUE THREAD

**Issue by stherold** [apple/swift-argument-parser#204]
I build a command line tool for accessing the App Store Connect API. Therefore I have a bunch of parsable commands. I now need the `verbose` flag but I want to implement it only once, e.g. via `ParsableArguments`. The thing is I don't want to use this flag in each single command but rather set it globally to `MyNetworkLayer.verbosityLevel`. Apparently I didn't find a way to read this value after it has been set so that I now misused the following way:
```swift
    mutating func validate() throws {
        // Misusing validate to set the received flag globally
        Network.verbosityLevel = verbose
    }
```

I wonder if there is  better way for this?

**Comment by natecook1000** [comment]
Interesting — so you've defined this as part of the root command, and use its value in `validate()`, but don't actually add this to your leaf commands?

**Comment by stherold** [comment]
Yep I added it like this:
```swift
/// Here you can specify parameters valid for all sub commands.
struct Options: ParsableArguments {

    @Flag(name: .shortAndLong, help: "Activate verbose logging. Prints e.g. the API response.")
    var verbose: Int

    mutating func validate() throws {
        // Misusing validate to set the received flag globally
        Network.verbosityLevel = verbose
    }
}
```

The reason why I didn't add it to all commands is because I have a bunch of them. I did the same with a token parameter but since this was @Option (or @Argument) and had a transform function I could use that one to access the argument once and set it globally. Aparrently @Flag doesn't have this...

**Comment by omarzl** [comment]
I solved it by creating a global var and setting the @Flag to the root command:
`public var isInVerboseMode = ProcessInfo.processInfo.arguments.contains("-v")`
not the best way but it works

**Comment by natecook1000** [comment]
This approach doesn't quite fit with `ArgumentParser`'s design — I look at each command/subcommand as analogous to a function call, with the options/flags/arguments as the parameters passed to that function. While it's convenient to have a global var set by a flag, you get away from the testability and reliability of having a function that relies only on its inputs.
