### ISSUE TITLE
Modifying help flag names does not work for subcommands

### ISSUE THREAD

**Issue by paulofaria** [apple/swift-argument-parser#215]
[modifying-the-help-flag-names](https://github.com/apple/swift-argument-parser/blob/master/Documentation/04%20Customizing%20Help.md#modifying-the-help-flag-names) does not work for subcommands. 

Possibly related to #36.

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

```swift
struct FeatherFeed : ParsableCommand {
    static var configuration = CommandConfiguration(
        abstract: "FeatherFeed backend application.",
        subcommands: [Run.self],
        defaultSubcommand: Run.self
    )

    ...
}


extension FeatherFeed {
    struct Run : ParsableCommand {
        static var configuration = CommandConfiguration(
            abstract: "Runs the FeatherFeed application.",
            helpNames: [.long, .customShort("?")]
        )
        
        @Option(name: .shortAndLong, help: "The host the server will run on.")
        var host: String = "::1"
        
        @Option(name: .shortAndLong, help: "The port the server will run on.")
        var port: Int = 8080
    
        ...
    }
}
```

### Expected behavior

```sh
> swift run feather-feed run --help
OVERVIEW: Runs the FeatherFeed application.

USAGE: feather-feed run [--host <host>] [--port <port>]

OPTIONS:
  -h, --host <host>       The host the server will run on. (default: ::1)
  -p, --port <port>       The port the server will run on. (default: 8080)
  -?, --help              Show help information.
```

### Actual behavior

```sh
> swift run feather-feed run --help
OVERVIEW: Runs the FeatherFeed application.

USAGE: feather-feed run [--host <host>] [--port <port>]

OPTIONS:
  -h, --host <host>       The host the server will run on. (default: ::1)
  -p, --port <port>       The port the server will run on. (default: 8080)
  -h, --help              Show help information.
```

### Discussion

Apparently subcommands are inheriting the `helpNames` configuration from the parent command. If I change `helpNames` for the `FeatherFeed` command, the `Run` subcommand inherits the `-?` flag.

**Comment by Zoha131** [comment]
@natecook1000 I have a question regarding this issue. Should Subcommands inherit `helpNames` from its parent if not modified? Or if not modified, `helpNames` for Subcommands would be `-h, --help` regardless how it is defined in the parent command?

**Comment by natecook1000** [comment]
I would think an inheritance model would make the most sense, and would be compatible with the current system. So subcommands get whatever their super-commands have specified, unless they specify their own. I think this means that we’d need to change the property to be optional and have it default to `nil`, however.
