### ISSUE TITLE
Completion Zsh when ArgumentParser helps contains `[`,`]`

### ISSUE THREAD

**Issue by miguelangel-dev** [apple/swift-argument-parser#218]
Declaring an `ArgumentParser` with the `help` containing one of these characters: `[` or `]`, it will conflict with the generated completion zsh-script.

example:
```swift
@Option(help: "This help contains invalid characters like [ or ]")
private var example: String
```

generate-completion-script:
```
    ...

    args+=(
        '--example[This help contains invalid characters like [ or ]]:example:'
        '(-h --help)'{-h,--help}'[Print help information.]'
    )

    ...
```

**ArgumentParser version:** `0.2.1`, `master`
**Swift version:** `5.3`
**Shell** oh-my-zsh / zsh

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Expected behavior
`--generate-completion-script zsh` command should alert about the invalid characters found in the `ArgumentParser:help`, and stop the process of generation script (failing).

### Actual behavior
It success the generation of the completion-script, but when you use the shell-completion, `zsh` throws some exceptions.

```
_arguments:comparguments:325: invalid option definition: --example[This help contains invalid characters like [ or ]]:example:
```

**Comment by Wevah** [comment]
Is there a reason `zshEscapingSingleQuotes()` uses `split()`/`join()` instead of `replacingOccurrences(of:with:)`?
