### ISSUE TITLE
Add convenience for printing to standard error

### ISSUE THREAD

**Issue by daltonclaybrook** [apple/swift-argument-parser#227]
ArgumentParser offers a few conveniences for printing to standard error, but as far as I can tell, all these mechanisms halt program execution (such as throwing or calling `Self.exit(withError:)`). It would be nice to be able to print to standard error without halting execution. It looks like ArgumentParser contains a `StandardError` type, but this type is internal. I suggest either making this type (and associated variable) public, or exposing a convenience function on `ParsableCommand` to print to standard error.

**Comment by below** [comment]
I have the bad feeling that I am probably stupid … but have you tried `fputs("Whoops! An error occurred: \(error)", stderr)` ?

**Comment by natecook1000** [comment]
@daltonclaybrook Thanks for opening the issue! I definitely agree that it's inconvenient to write to standard error right now. I think we should add support at a lower level than the ArgumentParser library, however. For now, you can use @below's suggestion or wrap it in a type that conforms to `TextOutputStream`, like ArgumentParser does.
