### ISSUE TITLE
Feature request: customizable enums-as-flags

### ISSUE THREAD

**Issue by belkadan** [apple/swift-argument-parser#24]
ArgumentParser has nifty support for enums-as-flags:

```swift
enum Compression: String, CaseIterable {
  case gzip, bzip2
}

@Flag()
var compression: Compression?
```

But it doesn't have any way to change the NameSpecification for individual cases, if you wanted to use something other than the default names. Or the ArgumentHelp, for that matter.

**Comment by belkadan** [comment]
Possible solution 1:

```swift
protocol MutuallyExclusiveFlag: CaseIterable, RawRepresentable where RawValue == String {
  static func overridingNameSpecification(for value: Self) -> NameSpecification?
  static func overridingHelp(for value: Self) -> ArgumentHelp?
}
```

Pros: simple, can go next to the cases
Cons: tied to the enum type rather than the parsed flag, which may reduce the enum's ability to be used for other things (though that's already a limitation today for enum-as-flag); not provided on each case (but that would require new language features)

**Comment by belkadan** [comment]
Possible solution 2:

```swift
extension Flag where Value: CaseIterable, Value: RawRepresentable, Value.RawValue == String {
  public init(
    name: (Value) -> NameSpecification = { _ in .long },
    default initial: Value? = nil,
    exclusivity: FlagExclusivity = .exclusive,
    help: (Value) -> ArgumentHelp? = { _ in nil }
  ) { … }
}
```

Pros: can be customized on a flag-variable-by-flag-variable basis
Cons: awkward to put a closure in there, so you'd still be defining a separate function anyway

**Comment by natecook1000** [comment]
I created a first draft of this with a partial piece of your solution 1 in #65. The design there so far is just:

```swift
public protocol EnumerableFlag: CaseIterable {
  static func name(for value: Self) -> NameSpecification
}
```

since we don't _need_ to have a string raw value, and a lot of times the exclusive cases can be shown with a single descriptive label. We may want to make it more like:

```swift
public protocol EnumerableFlag: CaseIterable {
  static func name(for value: Self) -> NameSpecification
  static func help(for value: Self) -> NameSpecification
  static var showDistinctHelpForEachCase: Bool { get }
}
```

so that users can choose whether to have that, or to treat each case as if it is its own separate flag. WDYT?

**Comment by belkadan** [comment]
Makes sense to me. One choice is whether `name(for:)` or `help(for:)` should be instance properties rather than static methods, since "one parameter of type `Self`" is kind of redundant with instance members, but then again it might be a *good* idea to demote these members out of code completion and such.

**Comment by natecook1000** [comment]
> then again it might be a good idea to demote these members out of code completion and such.

Exactly. Since we don't have a way to designate symbols like those as only really intended as protocol implementations, having them be static makes them feel a bit more like that.

**Comment by natecook1000** [comment]
Forgot to close this when I merged that PR long ago — @belkadan, please let me know if those customization points don't give you enough control.
