### ISSUE TITLE
Throwing a `CustomNSError` should exit with the custom error code

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#243]
If you throw an error type that conforms to `CustomNSError` from the `run` method or a validation closure, the exit code of the program should be the one given by the custom error type's `errorCode` property.

**ArgumentParser version:** `main` branch
**Swift version:** Apple Swift version 5.3

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Build and run this command, then use `echo $?` (or `echo $status` in fish) to inspect the exit code:

```swift
import ArgumentParser
import Foundation

enum CustomError: CustomNSError {
  case error
  
  var errorCode: Int {
    switch self {
    case .error: return 7
    }
  }
}

struct Example: ParsableCommand {
  func run() throws {
    throw CustomError.error
  }
}

Example.main()
```

### Expected behavior
The exit code should be 7.

### Actual behavior
It's actually 1, aka `EXIT_FAILURE`.

**Comment by lorentey** [comment]
This was a bad idea -- see #269.

**Comment by natecook1000** [comment]
Ugh, it seems so!
