### ISSUE TITLE
Is there a way to balance the processing of the argument with the "--version" option?

### ISSUE THREAD

**Issue by griffin-stewie** [apple/swift-argument-parser#25]
Is there a way to balance the processing of the argument with the "--version" option?

Here is my sample code. This command is simple echo, prints argument and prints version number if `--version` flag is applied.

```swift
import ArgumentParser

struct MyEcho: ParsableCommand {

    @Flag(name: .shortAndLong)
    var version: Bool

    @Argument()
    var text: String

    func run() {
        if version {
            print("v1.0.0")
            return
        }

        print(text)
    }
}

MyEcho.main()
```

However this sample code does not work well when you run `myEcho --version` because default validation by parser detects no argument. Like this

```sh
% myEcho --version
Error: Missing expected argument '<text>'
Usage: my-echo <text> [--version]
```

If I change `var text: String` property as optional, then `myEcho --version` works well but I have to handle a situation that no argument applied.

Here is my current solution bellow. Is there a better way to handle this situation?

```swift
struct MyEcho: ParsableCommand {

    @Flag(name: .shortAndLong)
    var version: Bool

    @Argument()
    var text: String?

    func run() throws {
        if version {
            print("ver 1.0.0")
            return
        }

        guard let text = text else {
            throw ValidationError("need argument")
        }

        print(text)
    }
}
```

**Comment by alexito4** [comment]
Related to version, it would be cool if `--version` came out of the box like help does. :)

**Comment by griffin-stewie** [comment]
@alexito4 
Yes! I really would like to have that support.

**Comment by natecook1000** [comment]
I think we probably should support `--version` directly. Here's a workaround until then:

```swift
struct Command: ParsableCommand {
    struct Version: ParsableArguments {
        @Flag() var version: Bool
        func validate() throws {
            if version { throw CleanExit.message("1.0.0") }
        }
    }
    
    @OptionGroup() var version: Version
    // ...
}
```

**Comment by griffin-stewie** [comment]
Thank you @natecook1000 I'll give it a try!

**Comment by griffin-stewie** [comment]
@natecook1000 
I tried your workaround and it works great! Thank you. However, I have come across a slightly mysterious behavior.

This code bellow prints `Error: Missing expected argument '<text>'` when I run `myEcho -v`

```swift
struct MyEcho: ParsableCommand {

    struct Version: ParsableArguments {
        @Flag(name: .shortAndLong) var version: Bool
        func validate() throws {
            if version { throw CleanExit.message("3.0.0") }
        }
    }

    struct Options: ParsableArguments {
        @OptionGroup()
        var version: Version

        @Argument()
        var text: String

        var url = URL(string: "https://apple.com")

        enum CodingKeys: String, CodingKey {
            case text
            case version
        }
    }

    @OptionGroup()
    var option: Options

    func run() throws {
        let text = option.text

        print(text)
    }
}

MyEcho.main()
```

When I fix `CodingKeys` declarations and struct's property declarations in the same order, then no longer cause problems.

Do I need to keep them in the same order?
