### ISSUE TITLE
Ignore `--help` flag when specified on a `cmd help subcommand` command

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#259]
As [noted here](https://github.com/realm/SwiftLint/issues/1088#issuecomment-745738042), adding the `--help` flag subverts the user's intent if they're trying to get help about a subcommand.

**ArgumentParser version:** `main` branch
**Swift version:** any

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
1. Build the project with `swift build`
2. Call the `math` command both the `help` subcommand and a `--help` flag, e.g. `.build/debug/math help stats --help`

### Expected behavior
It should print the help text for the `stats` subcommand.

### Actual behavior
It prints the help text for the top-level `math` command.

**Comment by Mark-McCracken** [comment]
I'd like to tackle this one if that's ok!

**Comment by natecook1000** [comment]
Sounds great, @Mark-McCracken!

**Comment by Mark-McCracken** [comment]
Added a PR here, would love your feedback!
https://github.com/apple/swift-argument-parser/pull/288
