### ISSUE TITLE
Parent command doesn't parse flags when a subcommand is invoked

### ISSUE THREAD

**Issue by varungandhi-apple** [apple/swift-argument-parser#266]
If you have a command with a subcommand, and the subcommand is invoked, the parent command's flags aren't parsed. Arguably, this is not the right behavior. Instead, first the parent should be allowed to parse its flags, then the subcommand should be run.

**ArgumentParser version:** `main`.
**Swift version:** 5.3.1.

### Checklist
- [X] If possible, I've reproduced the issue using the `main` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
```
import ArgumentParser

var GLOBAL_CHANGED_DIR: String? = nil

struct Outer: ParsableCommand {
  @Option(name: .customShort("C"))
  var changeDir: String?
  static var configuration = CommandConfiguration(
    abstract: "Test", subcommands: [Inner.self])
  func run() {
    GLOBAL_CHANGED_DIR = changeDir
    print("outer")
  }
}

struct Inner: ParsableCommand {
  func run() { print("inner") }
}

Outer.main()
```

### Expected behavior
Prints both "outer" and "inner"

### Actual behavior
Prints "inner"

### Why this should work

This is a very common pattern for command-line tools such as `ninja`, `cmake` and `git`, where some options are common between all sub-commands. (Note that I am using a global in the example here to work around Issue https://github.com/apple/swift-argument-parser/issues/254.)

The alternative of using `@OptionGroup` as advocated in the documentation duplicates the flags across multiple sub-commands, which may be undesirable as it hides the commonality between subcommands.

Although I do find the current default to be a bit strange, I'm open to the additional functionality being available through a different API, and not through `run` (to avoid breaking existing clients, or for some other reason).

**Comment by natecook1000** [comment]
@varungandhi-apple Thanks for opening this issue! The design is such that parsing always resolves to a single command or a failure, and only that single command is run. The parent/in-between commands on the way to the resolved command need to parse properly, but their run methods aren’t called, and as you noted they’re only made available to the resolved command if included using `@OptionGroup`.

I thought I had an issue open for grouping/naming `@OptionGroup`s in the help, but I don’t see it — I think that alleviates the undesirability of grouping.

**Comment by varungandhi-apple** [comment]
If I'm understanding #267 correctly, I don't think it will provide the behavior I want with subcommands. Here is my desired behavior (the help text could have some minor differences)

```
$ mytool --help
USAGE: mytool [-C <path>] <command> [<args>] 
$ mytool -C /path/to/dir dothing # okay
$ mytool help dothing
USAGE mytool [<args>] dothing [ ... subcommand-only args ... ]
$ mytool dothing -C /path/to/dir # error
```

Here is the behavior that I think the change in #267 will provide: (I might be misunderstanding, please correct me if so)

```
$ mytool --help
USAGE: mytool <subcommand> 
# other stuff...
$ mytool -C /path/to/dir dothing # okay
$ mytool help dothing
USAGE mytool dothing [-C <path>] [ ... subcommand-only args ... ]
OPTIONS:
  [... subcommand-only args ...]
SHARED OPTIONS:
  -C <path> ...
$ mytool dothing -C /path/to/dir # okay
```

I explicitly do not want arguments to be "splatted" in, instead I want to pass information from the parent to the child (via a parameter if possible as in #254, but a global is not a deal-breaker), and I want arguments/flags to be "scoped" (like a linked list of dictionaries) instead of being flat (like a single dictionary). A somewhat extreme example to illustrate this in action: with `git`, you can do `git -C /path/to/dir branch -C oldbranch newbranch`. The first `-C` changes the directory, whereas the second `-C` means that the branch ought to be copied.

Now, I don't want to get into a debate whether that's actually good design or not. What I'm trying to understand is whether ArgumentParser is flexible enough to be able to implement something the `git` example with two `-C`s. From what I can understand, it's not possible to do this at the moment, but maybe I'm missing how to use the library to do what I want.

**Comment by natecook1000** [comment]
> Now, I don't want to get into a debate whether that's actually good design or not. What I'm trying to understand is whether ArgumentParser is flexible enough to be able to implement something the git example with two -Cs. From what I can understand, it's not possible to do this at the moment, but maybe I'm missing how to use the library to do what I want.

Right, ArgumentParser doesn’t currently support that kind of usage, in a couple ways. First, option/flag names need to be unique in a command tree path — two different leaf commands can declare different `-C` options, but the root and a leaf cannot. Second, flags and options can be specified by the user anywhere in the command string, regardless of where they’re declared in the tool.

Thanks for the examples — that really helps make what you’re asking about more clear. I’ll keep thinking about whether it’s possible to support that kind of tool design while still maintaining ArgumentParser’s design goals.

**Comment by varungandhi-apple** [comment]
Got it, thanks. 👍🏼 

I'm okay if you would like to close this issue in case this is something that's not intended to be supported in the future. I probably need to roll my own solution anyways for now. 😅

**Comment by natecook1000** [comment]
You bet! Closing…
