### ISSUE TITLE
Dashes in command names break completion scripts

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#277]
Dashes aren't valid variable identifier characters for Zsh (~and maybe Bash~ just Zsh). When building a completion script for a command that includes one or more dashes in the command name, the completion script prints errors instead of providing completions.

**ArgumentParser version:** `main` branch
**Swift version:** Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Create a CLI tool with a dash in the command name, then generate and install a Zsh completion script for the command.

Command:
```swift
struct ExampleCommand: ParsableCommand {
  @Option var name: String
  @Flag var verbose = false
}
```

Script:
```
#compdef example-command
local context state state_descr line
_example-command_commandname=$words[1]
typeset -A opt_args

_example-command() {
    integer ret=1
    local -a args
    args+=(
        '--name:name:'
        '--verbose'
        '(-h --help)'{-h,--help}'[Print help information.]'
    )
    _arguments -w -s -S $args[@] && ret=0

    return ret
}


_custom_completion() {
    local completions=("${(@f)$($*)}")
    _describe '' completions
}

_example-command
```

### Expected behavior
Typing `example-command` and then `TAB` should offer completions.

### Actual behavior
The shell prints `_example-command:3: command not found: _example-command_commandname=example-command`.

**Comment by dhruvshah8** [comment]
Is this a problem with the ZshCompletionsGenerator or Parsing itself? I am having trouble finding exactly where the problem arises from, would appreciate any help. Thanks.

**Comment by natecook1000** [comment]
It's in the completions generator — specifically line 3 called out above, which creates a variable called `_example-command_commandname`. I think just changing any dashes in that variable name to underscores would do the trick.
