### ISSUE TITLE
Output of USAGE line in help is incorrect

### ISSUE THREAD

**Issue by fappelman** [apple/swift-argument-parser#278]
Under some conditions the Usage line in the generated help is incorrect.

**ArgumentParser version:** `0.3.2` 
**Swift version:** Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0

### Checklist
- [ ] If possible, I've reproduced the issue using the `main` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
There is a subtle bug in the `OptionGroup` help generation.

Given the following application:

```swift
struct ParserBug: ParsableCommand {
    static let configuration: CommandConfiguration = CommandConfiguration(
        commandName: "parserBug",
        subcommands: [Sub.self])

    func run() throws {
    }
}
```
which references a sub command named `Sub`:

```swift
extension ParserBug {
    struct Sub: ParsableCommand {
        @OptionGroup() var commonOptions: CommonOptions

        @Argument(help: "Mandatory argument") var argument: String
    }
}
```
which references a common option group `CommonOptions`:

```swift
extension ParserBug {
    struct CommonOptions: ParsableCommand {
        @Flag(help: "example flag") var example: Bool = false
    }
}
```
If I now run this application with the `parserBug sub -h` command, I get the following output:

```log
USAGE: parserBug sub [--example] <argument>

ARGUMENTS:
  <argument>              Mandatory argument 

OPTIONS:
  --example               example flag 
  -h, --help              Show help information.
```
and this output is completely as expected. I am now making one minor change in `Sub`:

```swift
extension ParserBug {
    struct Sub: ParsableCommand {
        @OptionGroup() var commonOptions: CommonOptions

        @Argument(help: "Mandatory argument")
        var argument: String? // <== Is now optional
    }
}
```
If I now run the help again the `USAGE` line is wrong:

```log
USAGE: parserBug common-options sub [--example] [<argument>]

ARGUMENTS:
  <argument>              Mandatory argument 

OPTIONS:
  --example               example flag 
  -h, --help              Show help information.
```
The word `common-options` should not be in the USAGE line.

I have used version `0.3.2`.
### Expected behavior
Usage without the word 'common-options'

### Actual behavior
Usage with the word 'common-options'

**Comment by natecook1000** [comment]
Note that this behavior doesn't show up if `CommonOptions` is declared as `ParsableArguments` instead of `ParsableCommand`. That means that it must be getting on the command stack incorrectly.
