### ISSUE TITLE
Document using @main to designate the root command

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-argument-parser#279]
ArgumentParser projects built using Swift PM or Xcode can now use the `@main` attribute to designate the root command instead of calling `Example.main()`. We should document that usage as the correct default approach.

**Comment by eaigner** [comment]
Except when I try to use `@main` it complains with

    'main' attribute cannot be used in a module that contains top-level code

**Comment by MPLew-is** [comment]
> ```
> 'main' attribute cannot be used in a module that contains top-level code
> ```

This error occurs when you have a `main.swift`; a top-level file and the `@main` attribute are mutually exclusive.

**Comment by jaredh159** [comment]
I still can't figure out how to get this to work -- If i rename `main.swift`, i just get 

```
executable product 'Example' expects target 'Example' to be executable; an executable target requires a 'main.swift' file
```

**Comment by el-hoshino** [comment]
↑Same here

**Comment by Ceylo** [comment]
For me the solution was to rename main.swift into something else while keeping @main. At first I had @main in main.swift which caused the error.

**Comment by Jerry-Carter** [comment]
I'm using Xcode 13.2 beta (13C5066c) on the async branch.  I found that using

Task {
  await program.run()
}

did not actually wait for the task to complete.  Instead, I (1) dropped the program.run() call at the top level, (2) renamed 'main.swift' to something else (e.g. command.swift) and (3) added a '@main' annotation to the ParsableCommand derived structure.

**Comment by natecook1000** [comment]
The documentation updates with 1.1.0 address this issue.
