### ISSUE TITLE
0.4.0 seems to think there's an argument var that doesn't actually exist

### ISSUE THREAD

**Issue by Wevah** [apple/swift-argument-parser#285]
Upon updating ArgumentParser to 0.4.0 (from 0.3.2), my project fails with the error "Error: No value set for non-argument var InputKey(rawValue: "products"). Replace with a static variable, or let constant."

`products` is a codable key on the `Config` struct; verified by changing the name. Removing the loading of that key also causes it to report the same error but with the next key down.

I'm using a custom struct called Config, and ArgumentParser seems to be trying to validate that object even though it doesn't conform to any of the ArgumentParser protocols, only `Decodable` (it loads a configuration from JSON in `run()`).

Seems to be caused the changes e99a8ef488533e3b331535902843230d2566d4ed.

Is there a way revert to the old behavior making it `static`?

**ArgumentParser version:** 0.4.0
**Swift version:** Apple Swift version 5.3.2

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Build the project in question with ArgumentParser 0.4.0.

### Expected behavior
Behavior should be the same as older versions.

### Actual behavior
The above error is reported.

**Comment by natecook1000** [comment]
@Wevah — are you able to link to the project, or post a stripped-down version that reproduces the issue?

**Comment by Wevah** [comment]
I'll post a stripped down version. I think I might be able to work around it by explicitly specifying the Codable keys for the containing object, but I'd like to avoid it if possible. (Going to add some extra info that I forgot to the OP also!)

**Comment by Wevah** [comment]
[bugexample.zip](https://github.com/apple/swift-argument-parser/files/6095794/bugexample.zip)

This reproduces the issue; using a version before the mentioned checkin doesn't trigger the error.

**Comment by natecook1000** [comment]
@Wevah Do you mind testing the branch in #286 against your actual project?

**Comment by Wevah** [comment]
That fixed it. Thanks!

**Comment by natecook1000** [comment]
Tagged a [new release](https://github.com/apple/swift-argument-parser/releases/tag/0.4.1) with this fix — thanks for the report!
