### ISSUE TITLE
Parsing strategy .optional

### ISSUE THREAD

**Issue by msalmonse** [apple/swift-argument-parser#307]
I wanted to add a `—draft` option to my command but I wanted to be able to optionally specify the draft text i.e. `—draft` or `—draft Entwurf`. Unfortunately I couldn't think of a way to handle it.

I think that there is a case for having optional arrays although I think there that specifying a minimum and maximum number of elements would be better.

I don't think that there is a good way of handling this with standard types so maybe a custom type should be a requirement, one that could take an optional value as an argument.

**Comment by msalmonse** [comment]
After giving it some thought I think that rather than flag and option a minimum and maximum number of arguments is more flexible. A flag is then 0…0, an option is 1…1, what I want is 0…1.

**Comment by swiftyfinch** [comment]
Sorry, I'm not sure that I understand you.
You can use `Flag` like 0 or 1 and `Option` like 0 or 1 as well. But also, `Option` can be an array. So it will be a collection with zero or more elements.

But I need the third state of `Option`:

```bash
Command                         | Swift
---------------------------------------------------------------------------------
rugby				| let focus: [String]? = nil
rugby --focus			| let focus: [String]? = []
rugby --focus Alamofire SnapKit | let focus: [String]? = ["Alamofire", "SnapKit"]
```

**Comment by msalmonse** [comment]
Not 0 or 1 but 0 to 1, it is a closed range of the number of arguments allowed, a flag has none or 0…0, an option 1…1 or 1… depending on your parsing strategy in the current setup.

**Comment by swiftyfinch** [comment]
I found that there is `init` with `initial: nil`. But when I run my command its demands this argument.

https://github.com/apple/swift-argument-parser/blob/992a7451d546ede8825284530ffdb541c9a316ef/Sources/ArgumentParser/Parsable%20Properties/Option.swift#L496-L509

**Comment by natecook1000** [comment]
This isn't currently supported, mostly because there isn't a great way to model it cleanly. It might make sense as a double Optional, but those are awkward to work with. Maybe we could add an Optional-esque type:

```swift
struct Example: ParsableCommand {
    @Option var kind: OptionValue<String>?

    func run() {
        print(kind as Any)
    }
}
```

```
$ example
nil
$ example --kind
.flagOnly
$ example --kind foo
.value(foo)
```

Still strikes me as a bit gross… Any other ideas?

**Comment by swiftyfinch** [comment]
Hey, @natecook1000 why we can use it like this:
```swift
@Option var kind: [String]?
```
Like it already works with non-collection types.

I can try to make a draft if it suits.
I see that need to change the array parsing strategy, but maybe there are some pitfalls.

**Comment by msalmonse** [comment]
I found another way to do it

**Comment by Jomy10** [comment]
@msalmonse Mind sharing your solution? :)

**Comment by msalmonse** [comment]
I wrote my own parser with a min and max count for parameters. I fixed the negative numbers problem as well and threw in environmental variables.

SAP is very good but… I remember a comparison of Windows with Linux: in Windows the easy is easy and the difficult is impossible while in Linux it's all just hard.

**Comment by Jomy10** [comment]
@msalmonse Thank you for the reply!
