### ISSUE TITLE
Improve handling of multiple optional arguments

### ISSUE THREAD

**Issue by adtrevor** [apple/swift-argument-parser#32]
Take the given program:
```swift
import ArgumentParser

struct ExampleCommand: ParsableCommand {
    @Argument()
    var arg1: String?
    
    @Argument()
    var arg2: String

    func run() {}
}

ExampleCommand.main()
```

Calling `./myProgram --help` shows:
```
USAGE: example-command [<arg1>] <arg2>

ARGUMENTS:
  <arg1>
  <arg2>

OPTIONS:
  -h, --help              Show help information.
```

Which would indicate `arg1` is optional, but omitting it:
```
`./myProgram isThisArg2??
```

Results in an error:
```
Error: Missing expected argument '<arg2>'
Usage: example-command [<arg1>] <arg2>
```

While optional arguments can easily cause ambiguous calls to your program, for instance if two arguments are optional and the program is only called with one argument, handling of such cases is probably improvable:
- Maybe non-ambiguous cases should be accepted, for instance, if in a total of `n` arguments there is a _single_ argument that's optional, accept calls with both `n` and `n-1` arguments, because we can suppose the "missing" argument is the optional one, this would make the above  example work.
- If there are other less obvious argument parsing strategies that enable avoiding ambiguities, they could be enabled through new options, for instance if in `some-command [<arg1>] [<arg2>] <arg3>` both `arg1` and `arg2` are restricted to two disjoint sets of acceptable values, its still possible to disambiguate a call with one **and** two arguments.
- In cases where we know there exists no way for the command to be called unambiguously, maybe it would be a good thing to crash as soon as possible in `.main()` (in debug builds) to let the code author know early there is something wrong with how they set the command arguments.

**Comment by natecook1000** [comment]
I don’t think we want to support a command design like this, since arguments are specifically assigned based on their position. I wouldn’t want to have the first input I give go to the second parameter, just because the first input is optional — that could lead to some really unexpected behaviors. Likewise, trying to select which argument an input can match by its value seems problematic.

I think your last point is right on. I’d like the ability to validate a command definition and looks for this kind of invalid construction. I’ll open a separate issue for that.

**Comment by adtrevor** [comment]
@natecook1000 I agree this can be confusing, especially something that would work like what I describe in the second point, but for the first point I wonder if this isn't something already too common in current CLIs not to be taken into account? For instance, take `git diff`: it accepts one or two arguments, and in this case its clear what the default value for the optional one is. Maybe it would be possible to limit optional arguments to a single one, and otherwise consider the command definition as invalid?
