### ISSUE TITLE
Parse issue when use withSingleDash and Name contains an "h"

### ISSUE THREAD

**Issue by SquircleCode-M** [apple/swift-argument-parser#327]
For this code
````
@Option(name: [.customLong("arrayArgumentWhatever", withSingleDash: true)],
            parsing: .upToNextOption,
            help: """
            Lorem IPSUM LOREM IMPSUM
            """)
    var arrayArgumentWhatever: [String]
````
When pass this:

`./Example --whatever value --whatever2 value --whatever3 value --whatever4 value --whatever5 value -arrayArgumentWhatever 03ade86c0 8f2058e3ade86c84ec5b`

The argument  in function `func checkForBuiltInFlags(_ split: SplitArguments)` contains an h, so cli displays help

```
64 : -h
      ▿ value : Value
        ▿ option : -h
          ▿ name : Name
            ▿ short : 2 elements
              - .0 : "h"
              - allowingJoined : false
```

**ArgumentParser version:** `0.4.3`
**Swift version:** swift-driver version: 1.26 Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)
Target: x86_64-apple-macosx11.0

### Checklist
- [X] If possible, I've reproduced the issue using the `main` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

**Comment by natecook1000** [comment]
Thanks for the report, @SquircleCode-M! Seems like the `-arrayArgumentWhatever` isn't correctly getting marked as used when specified with `.upToNextOption` — I don't see this issue without that parameter.

**Comment by natecook1000** [comment]
Minimal example:

```swift
struct Example: ParsableCommand {
  @Option(name: .customLong("arrayArgumentWhatever", withSingleDash: true),
          parsing: .upToNextOption)
  var arrayArgumentWhatever: [String]
  
  mutating func run() {
    print(arrayArgumentWhatever)
  }
}

Example.main()
```
