### ISSUE TITLE
Add ability to determine if Option/Flag/etc was passed explicitly to the app

### ISSUE THREAD

**Issue by ileitch** [apple/swift-argument-parser#330]
I'm working on an app that supports persisting configuration to a YAML file. When the app boots, configuration is read from the YAML, followed by arguments from the command line. I only want to apply the command line value if it was explicitly provided, otherwise the value from the YAML is used. Currently I've implemented this as follows:

```swift
@Flag(help: "Some flag.")
var someFlag: Bool = false

func run() throws {
    let config = Configuration()
    config.loadFromYAML()

    if CommandLine.arguments.contains({ $0.hasSuffix("some-flag") }) {
        config.someFlag = someFlag
    }
}
```

This works, but the need to duplicate the argument name isn't great. I'd like for SAP to handle this ability, or at least expose the flag name somehow. I'm thinking a `projectedValue` from the property wrapper might be a nice solution, e.g:

```swift
if $someFlag.isExplicit {
    config.someFlag = someFlag
}
```

Thoughts?

**Comment by natecook1000** [comment]
@ileitch Are you trying to do this with an option with a default value? In your example, the only way `someFlag` ends up `true` is if it's given on the command line explicitly, otherwise it's false.

**Comment by ileitch** [comment]
Yes I'm using both Options and Flags with default values. I see your point that I could do `if someFlag != false { config.someFlag = true }`, yet I'd need to duplicate the default values, or house them in some separate data structure. That's totally fine of course, just perhaps not quite as elegant as using a projected value property?
