### ISSUE TITLE
v0.4.3 crashs when using Transform closure

### ISSUE THREAD

**Issue by griffin-stewie** [apple/swift-argument-parser#338]
It crashes(SIGABRT) on Release build when I use Transform closure.

I tested several versions bellow. Only v0.4.3 has this issue.

- ✅ 0.3.2
- ✅ 0.4.0
- ✅ 0.4.1
- ✅ 0.4.2
- ‼️ 0.4.3
- ‼️ main branch

**ArgumentParser version:** `0.4.3`
**Swift version:** Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55) Target: x86\_64-apple-darwin20.5.0

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

[Here](https://github.com/griffin-stewie/sample_cal) is my sample code to reproduce this issue.

1. Build sample code with Release configuration.
2. Run this `sample_cal description --start-date 2021/07/18_11:22:33 --name aaa`

I suspect that the crash is caused by using `@Option(name: , help: , transform: )`.

One more thing, It prints a blank where `start: Date` should be printed, if I deleted `@Option() var name: String`.

### Expected behavior

No crash, and prints OptionGroup’s description.

### Actual behavior

Crashed.

Xcode shows some logs on console, like bellow:

```
sample\_cal(687,0x10026fe00) malloc: Double free of object 0x105a47cc0
sample\_cal(687,0x10026fe00) malloc: \*\*\* set a breakpoint in malloc\_error\_break to debug
```

**Comment by rauhul** [comment]
I played around with your sample code in Xcode and on the command line. I tried reducing the example and had a wild amount of non deterministic results based on: clean vs incremental builds, `Date` vs `Int`, etc... To me, this screams mis-compile and not library bug. Additionally, one of crashes modes I've seen is an `EXC_BAD_ACCESS ` in the `as?` operator which is also very suspicious.

```
Apple Swift version 5.3.1 (swiftlang-1205.0.16.11 clang-1205.0.19.6)
Target: x86_64-apple-darwin20.3.0
SAP: 0.4.3 & ee32b809403dc77bded883194e3bbcb107be5104
```

**Comment by natecook1000** [comment]
Thanks for the detailed report, @griffin-stewie!

**Comment by griffin-stewie** [comment]
Thanks @natecook1000 and @rauhul !

**Comment by griffin-stewie** [comment]
I've tested [my sample code](https://github.com/griffin-stewie/sample_cal/tree/update_to_v0_4_4) with the latest ArgumentParser v0.4.4. Everything works great!
