### ISSUE TITLE
Error when using @Option

### ISSUE THREAD

**Issue by Blackjacx** [apple/swift-argument-parser#34]
Hey Paul, 

first of all: really cool project! Thanks a lot :-)

I have the following in my small (private) script which should specify the Xcode project root:

```
    @Option(name: .shortAndLong, help: "The root directory of your Xcode project.")
    var projectRoot: String
```

The running `swift build && swift run downloadmetadata --projectRoot .` gives me the error:

```
Fatal error: Trying to read value from definition.: file /Users/stherold/dev/projects/db/ios-tools/.build/checkouts/swift-argument-parser/Sources/ArgumentParser/Parsable Properties/Option.swift, line 48
[1]    55885 illegal hardware instruction  swift run downloadmetadata --projectRoot .
```

Any idea?

**Comment by natecook1000** [comment]
This happens when you instantiate your command type with the empty initializer (like `let command = MyCommand()`) instead of calling one of the parsing methods. You probably want to write `MyCommand.main()` instead.

**Comment by Blackjacx** [comment]
Ahhh thx :-)
