### ISSUE TITLE
ExpressibleByArgument, CaseIterable for enum not listing options during failure

### ISSUE THREAD

**Issue by BadPirate** [apple/swift-argument-parser#344]
When using ExpressibleByArgument for an enum @Option, neither help nor error message correctly shows available options.

**ArgumentParser**: main
**Swift version:** Apple Swift version 5.3.1

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Create an option:

```
    enum Config : String, ExpressibleByArgument, CaseIterable
    {
        case ios, mac, simulator
    }
    
    @Option(help: "Build configuration")
    var config : [Config] = [.ios]
```

See command help screen using -h, or use the config option with an illegal value:

```
cli command --config invalid
```

### Expected behavior
1. Help should show options available
2. Error message should show valid options

### Actual behavior

1. Help Provides no options.
2. Error provides no useful options:
  
  ```
  Error: The value 'invalid' is invalid for '--config <config>'
  Usage: cli command [--config <config> ...] 
    See 'cli command --help' for more information.
  ```

**Comment by natecook1000** [comment]
Resolved by #382.
