### ISSUE TITLE
Async branch not working with Xcode 13 Beta 5

### ISSUE THREAD

**Issue by Blackjacx** [apple/swift-argument-parser#345]
I just installed Xcode 13 Beta 5 13A5212g and now I get the errors below when building my root package [Assist](https://github.com/Blackjacx/Assist/tree/async-await) from branch `async-await`. In a previous version this worked without problems. I just upgraded macOS to the newest beta and downloaded the latest Xcode. I wonder why you don't specify any platform versions in Package.swift. Since Async await is only working in macOS 12 and argument parser is only for macOS I'd expect something like 

```
platforms: [
    .macOS(.v12)
]
```

The errors I get are the following:

```
~/Library/Developer/Xcode/DerivedData/Assist-bpeugmbecnlglscpsxjqdloqyduu/SourcePackages/checkouts/swift-argument-parser/Sources/ArgumentParser/Parsable Types/ParsableCommand.swift:31:23: error: concurrency is only available in macOS 12.0.0 or newer
  mutating func run() async throws
```

![Screen Shot 2021-08-18 at 15 13 06](https://user-images.githubusercontent.com/794372/129904239-b0af90e5-bdf8-4825-ba96-edee81f77f58.png)

I can build my package on command line via 
`swift build "-Xswiftc" "-target" "-Xswiftc" "x86_64-apple-macosx12.0"`

But not in Xcode :(

Anything I'm missing?

**Comment by natecook1000** [comment]
This should be resolved, see #404 for latest.
