### ISSUE TITLE
Support CocoaPods

### ISSUE THREAD

**Issue by racer1988** [apple/swift-argument-parser#348]
We are unable to use SPM, can you support CocoaPods

**Comment by lorentey** [comment]
We currently provide full support for building this package with the Swift Package Manager and Xcode, as well as limited support for CMake (only for bootstrapping purposes within the Swift project, not for general use).

We have no plans to support additional build systems or package managers.

If these don't fit your use case, one option is to vendor the modules you need within your own project. (As always, make sure you follow the conditions of the license.)

**Comment by racer1988** [comment]
That's unfortunate.
Lot of people are still in need of use Cartage and CocoaPods

**Comment by keith** [comment]
FYI someone created a podspec with the name `ArgumentParser` to use https://github.com/CocoaPods/Specs/blob/419a93a939503f0ec5ee87f0a27585f93fad3bee/Specs/a/4/d/ArgumentParser/1.2.0/ArgumentParser.podspec.json
