### ISSUE TITLE
Initializing a `ParsableCommand` with a value does not work, but setting it after initialization does.

### ISSUE THREAD

**Issue by acoomans** [apple/swift-argument-parser#359]
Initializing a `ParsableCommand` with a value does not work, but setting it after initialization does.

**ArgumentParser version:** `0.3.0`
**Swift version:** `swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1) Target: x86_64-apple-macosx11.0`

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

Set up a `ParsableCommand` with 2 independent sub-`ParsableCommand`, and 1 `all` sub-`ParsableCommand` that runs both of the sub-`ParsableCommand`:

```
import Foundation
import ArgumentParser

enum EndpointFlag: String, EnumerableFlag {
    case local
    case staging
    case prod
}

struct SwiftScript: ParsableCommand {

    static var configuration = CommandConfiguration(
            subcommands: [DownloadSchema.self, GenerateCode.self, DownloadSchemaAndGenerateCode.self])

    struct DownloadSchema: ParsableCommand {
        static var configuration = CommandConfiguration(...)

        @Flag(exclusivity: .exclusive, help: "...") var endpointFlags: EndpointFlag = .local
        
        func run() throws {...}
    }
    
    struct GenerateCode: ParsableCommand {
        static var configuration = CommandConfiguration(...)
        
        func run() throws {...}
    }

    struct DownloadSchemaAndGenerateCode: ParsableCommand {
        static var configuration = CommandConfiguration(...)

        @Flag(exclusivity: .exclusive, help: "...") var endpointFlags: EndpointFlag = .local

        func run() throws {
		
			// working code
			var downloadSchema = DownloadSchema()
			downloadSchema.endpointFlags = endpointFlags
			try downloadSchema.run()
			// end working code
		
			// NOT working code
			try DownloadSchema(endpointFlags: endpointFlags).run()		
			// end NOT working code

			try GenerateCode().run()
        }
    }
}

SwiftScript.main()
```

### Expected behavior

When called with `swift run SwiftScript downloadSchemaAndGenerateCode`, it should run both commands successfully, i.e:

1. run `DownloadSchemaAndGenerateCode`, take its `endpointFlags` value, and 
2. pass it down to `DownloadSchema`, which should run with the right `endpointFlags` value, and 
3. finally run `GenerateCode`.

### Actual behavior

`swift run SwiftScript downloadSchemaAndGenerateCode` stops and outputs the following error message:

```
ArgumentParser/Flag.swift:103: Fatal error: 
--------------------------------------------------------------------
Can't read a value from a parsable argument definition.

This error indicates that a property declared with an `@Argument`,
`@Option`, `@Flag`, or `@OptionGroup` property wrapper was neither
initialized to a value nor decoded from command-line arguments.

To get a valid value, either call one of the static parsing methods
(`parse`, `parseAsRoot`, or `main`) or define an initializer that
initializes _every_ property of your parsable type.
--------------------------------------------------------------------

zsh: illegal hardware instruction  swift run SwiftScript all --staging
```

**Comment by natecook1000** [comment]
This is the expected behavior — due to the property wrappers, all the properties in your commands have a default value. This results in an automatically-generated empty initializer (e.g. `init()`), so you’ll need to create your own memberwise initializer if you’d like to construct a command manually. A hint: put that additional init in an extension instead of the original declaration, or else you might suppress the auto-generated version.

**Comment by willswire** [comment]
I recently ran into this same problem as well, and for anyone looking for help, here's what worked for me:

The main command struct:
```swift
@main struct Cosmic: AsyncParsableCommand {
    static var configuration = CommandConfiguration(
        abstract: "A package manager for macOS.",
        subcommands: [Setup.self, Add.self])
    
    struct Options: ParsableArguments {
        @Flag(name: [.long, .customShort("v")]) var verbose: Bool = false
    }
}```

The subcommand structure:
```swift
extension Cosmic {
    struct Setup: AsyncParsableCommand {
        static var configuration = CommandConfiguration(abstract: "Setup the Cosmic package manager.")
        @OptionGroup var options: Cosmic.Options
     ...
     }
}
```

Constructing a command manually somewhere:
```swift
@Test("Set up Cosmic")
func setUpCosmic() async throws {
    var setupCommand = Cosmic.Setup()
    setupCommand.options = try .parse(["--verbose"])
    ...
}
```

The root cause is as @natecook1000 mentioned - automatically-generated empty initializers for subcommands do not provide an initial value for these OptionGroups. Therefore, we must set them, and I think the most straightforward way to do that is the [parse](https://apple.github.io/swift-argument-parser/documentation/argumentparser/parsablearguments/parse(_:)) function, not an initializer.
