### ISSUE TITLE
Swift Concurrency support

### ISSUE THREAD

**Issue by griffin-stewie** [apple/swift-argument-parser#368]
Xcode 13.2 Beta is released now. We are getting closer to use Swift Concurrency in the real life. I wish [async branch](https://github.com/apple/swift-argument-parser/tree/async) will be merged.

Thank you.

**Comment by Jerry-Carter** [comment]
This seems like a duplicate of [Issue #326](https://github.com/apple/swift-argument-parser/issues/326)

**Comment by natecook1000** [comment]
Tracked in #326.
