### ISSUE TITLE
Support a --version or -v option without required arguments

### ISSUE THREAD

**Issue by leisurehound** [apple/swift-argument-parser#378]
its currently possible to add a -v version option to display the version of the application, however it requires any arguments to be set as optional and when -v is not supplied and the argument is also not provided, forces users to roll their own error condition for a missing argument.

Ideally, it would be better if a -v could be inherent like the -h, such that the required argument checking is bypassed and the version is simply reported without error and when the argument is missing and no -v is provided the normal error reporting is displayed.

**Comment by natecook1000** [comment]
ArgumentParser has built-in version support under the `--version` flag if you specify a version string as part of your command configuration. We don’t provide it for the -v flag, since that frequently is used for “verbose” instead of the version.

**Comment by leisurehound** [comment]
Fair enough.  but not very discoverable.  Would you want a PR to add something like 'for further configuration of the library for your use, see CommandConfiguration and create a static instance in your ParsableCommand' to the readme?

**Comment by leisurehound** [comment]
Sorry to open this again, but does this still work?

```
@main
struct PingCommand : ParsableCommand {

  var version: String = "v1.0.1"
  @Argument(help: "Device ID")
  var deviceID: String


  func run() throws {
    let pingProcessor = PingProcessor()
    pingProcessor.start(deviceID: deviceID)
  }

}
```

and I get the following error from `PingCommand --version`

```
Error: Unknown option '--version'
Usage: ping-command <device-id>
  See ping-command --help' for more information.
```
The [documentation](https://swiftpackageindex.com/apple/swift-argument-parser/1.2.2/documentation/argumentparser/commandconfiguration/version) does appear correct, but is it complete?  What else needs to be set?

**Comment by rauhul** [comment]
> Sorry to open this again, but does this still work?
> 
> 
> 
> ```
> 
> @main
> 
> struct PingCommand : ParsableCommand {
> 
> 
> 
>   var version: String = "v1.0.1"
> 
>   @Argument(help: "Device ID")
> 
>   var deviceID: String
> 
> 
> 
> 
> 
>   func run() throws {
> 
>     let pingProcessor = PingProcessor()
> 
>     pingProcessor.start(deviceID: deviceID)
> 
>   }
> 
> 
> 
> }
> 
> ```
> 
> 
> 
> and I get the following error from `PingCommand --version`
> 
> 
> 
> ```
> 
> Error: Unknown option '--version'
> 
> Usage: ping-command <device-id>
> 
>   See ping-command --help' for more information.
> 
> ```
> 
> The [documentation](https://swiftpackageindex.com/apple/swift-argument-parser/1.2.2/documentation/argumentparser/commandconfiguration/version) does appear correct, but is it complete?  What else needs to be set?
> 
> 

The `version` property must be part of your command configuration.
