### ISSUE TITLE
Add `isExperimental` parameter to Flag/Option

### ISSUE THREAD

**Issue by KS1019** [apple/swift-argument-parser#394]
This issue proposes a new bool parameter `isExperimental` to Flag and Option. 

## How it can be useful
With this parameter, we can possibly
- Automatically add `experimental` prefix
- Automatically remove the experimental Flags/Options from the help
- Automatically mark the experimental Flags/Options as experimental in the dumped JSON by `--experimental-dump-help`
- Only list experimental Flags/Options

With this parameter, users of ArgumentParser can easily mark Flag/Option as experimental and control the exposure of the Flag/Option to users of their tool.

**Comment by natecook1000** [comment]
Thanks for opening this, @KS1019! I think I'd like to leave this feature out, since you can implement these individual pieces using existing functionality, and I'd like for users of the library to be able make their own decisions about transitioning from experimental to supported features, etc.
