### ISSUE TITLE
Packages using ArgumentParser which support older platforms can no longer compiler (since 1.1.0)

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-argument-parser#426]
Packages depending on swift-argument-parser which support older platforms are no longer able to compile.

This is a regression introduced in 1.1.0 where supported platforms were added to the package manifest. This raised the supported platforms from the defaults. This is a breaking change as packages depending on swift-argument-parser which support platforms older than those supported by this package are no longer able to compile (SPM will not resolve to a version of the package where appropriate platforms are supported).

Packages depending on swift-argument-parser must either raise their own supported platforms, require the version of swift-argument-parser to be less than 1.1.0, or remove their requirement on swift-argument-parser. 

**ArgumentParser version:** `1.1.0`

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

**Comment by Lukasa** [comment]
Yup, this is a semver major: this has to be backed out and submitted in a 2.0.0.
