### ISSUE TITLE
Debug assert to catch AsyncParseableCommand hierarchy issues

### ISSUE THREAD

**Issue by rauhul** [apple/swift-argument-parser#433]
It would be nice to add a code path in debug mode that asserts if a user has accidentally included an AsyncParseableCommand nested under a Sync one, as the async run entry point will not be called in this case.

**Comment by KeithBird** [comment]
> It would be nice to add a code path in debug mode that asserts if a user has accidentally included an AsyncParseableCommand nested under a Sync one, as the async run entry point will not be called in this case.

typo: `AsyncParseableCommand` -> `AsyncParsableCommand` 😊

**Comment by KeithBird** [comment]
Does the following code correctly express this issue?

```swift
struct Math: ParsableCommand {
  static var configuration = CommandConfiguration(
    subcommands: [Add.self]
  )

  struct Add: AsyncParsableCommand {
    @Argument() var values: [Int] = []
  }
}

// Error: `Add` subcommand can't run asynchronously in `Math`
```

**Comment by MarcoEidinger** [comment]
@rauhul is the issue fixed with https://github.com/apple/swift-argument-parser/pull/436 ? Then issue can be closed

**Comment by rauhul** [comment]
Yes, good catch, verified locally.
