### ISSUE TITLE
[GSoC] CLI design for interactive mode

### ISSUE THREAD

**Issue by KeithBird** [apple/swift-argument-parser#448]
The following internal functions will serve as the basis for the interactive mode:

### `Ask` prompt the user for input:

```swift
let operand = ask("? Please enter operand: ", type: Int.self)
```

```
? Please enter operand: 1.2
Error: The type of '1.2' is not Int.

? Please enter operand: 1
```

### `Choose` provides possible input for the user to choose from:

```swift
let choice = choose("? Please select an operator: ", from: ["+", "-", "*", "/"])
```

```
1. +
2. -
3. *
4. /
? Please select an operator: +
Error: '+' is not a serial number.

? Please select an operator: 0
Error: '0' is not in the range 1 - 4.

? Please select an operator: 1
You select '+'.
```

### `Check` verifies key directives

```swift
guard check("Are you sure you want to delete all?") else { return } 
```

```
Are you sure you want to delete all? 
? Please enter [y]es or [n]o: y
```

---

**This issue is posted here as a subtask of the [GSoC project](https://github.com/apple/swift-argument-parser/issues/449) for discussion and suggestions.**

**Comment by natecook1000** [comment]
@KeithBird Now that your prototype is largely implemented, let's look again at the design of these functions. The goal is that these could eventually be exposed as public API, so the design should be separate from their use in this interactive project. What parameters will you need to accomplish that?
