### ISSUE TITLE
This package no longer builds in release mode on linux

### ISSUE THREAD

**Issue by buttaface** [apple/swift-argument-parser#463]
Building in release mode produces this since #410 was merged:
```
> ./swift-5.6.2-RELEASE-ubuntu20.04/usr/bin/swift build -c release
/home/butta/swift-argument-parser/Sources/ArgumentParserTestHelpers/TestHelpers.swift:12:18: error: module 'ArgumentParser' was not compiled for testing
@testable import ArgumentParser
```
That means the last working version was 1.0.3. A workaround is to add `-Xswiftc -enable-testing`.

**ArgumentParser version:** latest commit df9ee66 from the  `main` branch
**Swift version:** 5.5 and later, probably earlier versions too

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

**Comment by natecook1000** [comment]
@buttaface Could you verify that this issue is resolved with the latest version of `main`?

**Comment by buttaface** [comment]
Yep, works now, thanks. 😄
