### ISSUE TITLE
Including `transform:` parameter in `@Argument` declaration generates wrong help message for optional arguments

### ISSUE THREAD

**Issue by YourMJK** [apple/swift-argument-parser#466]
Declaring an argument with `@Argument(..., transform:)` makes it non-optional in the "USAGE" and doesn't include it's default value in the argument's abstract in the "ARGUMENTS" section, ***even* if the value has a default value and/or is of an optional type.**  
(The actual parsing of the optional arguments seems to be correct)

**ArgumentParser version:** `1.1.3`
**Swift version:** `swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)`

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Declare arguments like this in a `ParsableCommand` struct:
```
struct Cmd1: ParsableCommand {
  @Argument(help: "Test argument 1", transform: { Int($0)! })
  var test1: Int = 0
  
  @Argument(help: "Test argument 2", transform: URL.init(fileURLWithPath:))
  var test2: URL?
}
```
and print the help message through `Cmd.parseOrExit([])` or `print(Cmd.helpMessage())`

### Expected behavior
The printed help string (namely USAGE and ARGUMENTS) should be the same as if the arguments were declared like this (without the `transform:` parameter):
```
struct Cmd2: ParsableCommand {
  @Argument(help: "Test argument 1")
  var test1: Int = 0
  
  @Argument(help: "Test argument 2")
  var test2: String?
}
```

### Actual behavior
Help message for arguments with `transform:` parameter looks like this:
```
USAGE: cmd1 <test1> <test2>

ARGUMENTS:
  <test1>                 Test argument 1
  <test2>                 Test argument 2
```
While help message *without* `transform:` is correctly generated:
```
USAGE: cmd2 [<test1>] [<test2>]

ARGUMENTS:
  <test1>                 Test argument 1 (default: 0)
  <test2>                 Test argument 2
```

**Comment by rauhul** [comment]
Hey @YourMJK this is actually working as intended. By using `transform` you opt out of using `ExpressibleByArgument` which means you lose out on the default value getting printed. However while investigating the issue I did find a number of other help generation bugs which I have included in 477.

**Comment by YourMJK** [comment]
Thanks for the response.  

This doesn't make much sense to me and I'm not sure if it's working as intended.  
To clarify, I'm talking about the usage string that's being generated.

I would expect that declaring any argument of an optional type like this:  
`var arg0: T?`  
to produce a usage string like this:  
`USAGE:  cmd [arg0]`  
regardless of whether a transform closure is specified or not.  

This is currently not the case. Instead it's  
`USAGE:  cmd <arg0>`

I don't understand why I can't have an optional argument when I specify the transform closure.  
I can't see any technical reason that would make it impossible to implement this (IMO expected) behavior.

**Comment by rauhul** [comment]
Sorry I misspoke, you are correct that the "Optionality" of the argument should be preserved regardless of transform vs ExpressibleByAgrument. I meant to say that the `(default: 0)` will not occur for the transform path.

**Comment by YourMJK** [comment]
I see, thanks for the clarification.

**Comment by rauhul** [comment]
Give main a try, the bug should be resolved!
