### ISSUE TITLE
Not parsing positional argument

### ISSUE THREAD

**Issue by RISCfuture** [apple/swift-argument-parser#489]
I have a `ParsableCommand` instance with two positional arguments, one of which is required. Despite passing a value for the required argument, it still claims that argument is not being specified.

**ArgumentParser version:** `main`
**Swift version:** 5.7.0.127.4

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

``` swift
import Foundation
import ArgumentParser

@main
struct ExampleCommand: ParsableCommand {
    @Argument(help: "arg1",
              completion: .file(extensions: ["sql"]),
              transform: URL.init(fileURLWithPath:))
    var firstArg = URL(fileURLWithPath: "default/value.sql")
    
    @Argument(help: "arg2",
              completion: .file(extensions: ["csv"]),
              transform: URL.init(fileURLWithPath:))
    var secondArg
    
    @Flag(help: "Include extra information in the output.")
    var verbose = false
    
    mutating func run() throws {
      print(firstArg, secondArg)
    }
}
```

Run `example-command some/file.csv`

### Expected behavior

Prints the two arguments.

### Actual behavior

```
Error: Missing expected argument '<second-arg>'
Help:  <second-arg>  arg2
Usage: example-command [<first-arg>] <second-arg> [--verbose]
  See 'example-command --help' for more information.
Program ended with exit code: 64
```

**Comment by natecook1000** [comment]
This is behaving as intended, since positional arguments are always filled in declaration order. It would be nice if we had a warning or validation error for commands with this configuration, so that you don't have to wonder what's going on.
