### ISSUE TITLE
Warning "Conversion to Swift 5 is available" in Xcode 14

### ISSUE THREAD

**Issue by chrisyarbrough** [apple/swift-argument-parser#513]
Argument parser is generating the warning "Conversion to Swift 5 is available" in Xcode 14.0.1 (14A400). 

**ArgumentParser version:**
1.1.4

**Swift version:**
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
- Create a Swift Command Line Application in Xcode
- Import ArgumentParser with any sample code and build
- Observe Xcode warnings in the Navigator

### Expected behavior
No warnings should be shown.

### Actual behavior
The Xcode navigator shows this warning: warning project: Conversion to Swift 5 is available

Clicking the warning normally allows auto-upgrading the code to a newer version. In this case, however, auto-upgrade will not work. It will display the message "No source changes necessary". Presumably, it's not possible to auto-upgrade the code because package dependencies are readonly and should not be modified. To remove the warning, the source code of the ArgumentParser package will need to conform to Swift 5.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/17833862/198854559-e282b189-5495-4d63-9da6-cee336fadb14.png">

**Comment by natecook1000** [comment]
Odd! This package requires at least Swift 5.5, so I don't know what would be flagging that conversion flow. I can't reproduce with the same setup, fwiw.

**Comment by chrisyarbrough** [comment]
Thanks for checking! In the meantime, I wasn't able to reproduce the issue again and I accidentally deleted the original project with the warning showing. I guess it doesn't make sense, so maybe there was some other strange configuration that caused Xcode to stumble.
