### ISSUE TITLE
Dynamic command line completions

### ISSUE THREAD

**Issue by hassila** [apple/swift-argument-parser#559]
Current SAP can generate a custom list of completions (which is nice!), it'd be even cooler if this could be expanded to real "live" completions with approaches similar to (https://unix.stackexchange.com/questions/227826/how-to-implement-dynamic-bash-auto-completion) - if I'm not misunderstanding the current state of affairs, the custom completions currently are run only once when the completion script is generated - what I'm after is that the completion would run the tool and dynamically generate the completions.

Sample use cases:

* Completion of e.g. available table names in a database names (that can change between invocations)
* Completion of internal state of a server (a client CLI tool can connect to the server and complete state dynamically), could be useful for introspection tools - this is what I'm looking at at the moment and this would have been quite useful

I think most of the infrastructure is in place, there just needs to be some way to invoke the SAP tool and get it to return the list of completions in a way the shell needs (as the link above does for example) and tweak the completion scripts to do 'live' queries when desired. 

Extra nice would be to support caching of the dynamic results in an easy way (for cases where it is potentially expensive, the dynamic query could choose to just return cached results).

WDYT?

**Comment by natecook1000** [comment]
You can configure dynamic completions when declaring an argument or option by specifying a `CompletionKind`. That configuration has options for both calling out to a command-line script and providing a closure that returns the list of completions — you can see the [API documentation](https://swiftpackageindex.com/apple/swift-argument-parser/1.2.2/documentation/argumentparser/completionkind) or this article for more: https://swiftpackageindex.com/apple/swift-argument-parser/1.2.2/documentation/argumentparser/customizingcompletions

**Comment by hassila** [comment]
@natecook1000 that just generates a dynamic set of completions when the completion scripts are generated afaict and I played with it before opening this issue (it seems clear that those dynamic completions are a hardcoded part of the generated completion scripts, at least when I inspected the output) . 

That's not what I'm writing about above - I'm talking about true dynamic completions where I don't need to rerun and reapply the completion scripts - to allow for completion on things that change often and to not have to rerun the generation and apply completion scripts to pickup changes to the dynamic set of options. 

Maybe we are talking past each other or I'm missing something.
