### ISSUE TITLE
Add possibility for subcommand to show help text by default

### ISSUE THREAD

**Issue by revolter** [apple/swift-argument-parser#560]
Similar to how `pod cache` works, meaning, it outputs the same thing as `pod cache --help`, it would be nice if this package would support it as well.

I tried this hacky workaround:
```swift
@Flag
var help = true
```
but it fails with the error
```
ArgumentParser/ParsableArguments.swift:256: Fatal error: Validation failed for `ConfigCommand`:

- One or more Boolean flags is declared with an initial value of `true`.
This results in the flag always being `true`, no matter whether the user
specifies the flag or not.

To resolve this error, change the default to `false`, provide a value
for the `inversion:` parameter, or remove the `@Flag` property wrapper
altogether.

Affected flag(s):
--help
```

**Comment by natecook1000** [comment]
This is the default for how commands should work — can you provide an example of this not working as expected?

**Comment by revolter** [comment]
Oh, I thought that the `run` function is required, and I also didn't read its documentation.
