### ISSUE TITLE
An array with no default value should be interpreted as an argument with at least one required element

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-argument-parser#569]
```swift
struct Example: ParsableCommand {
    @Argument var files: [String] = []
    @Option var count: Int?
    @Option var index = 0
    @Flag var verbose = false
    @Flag var stripWhitespace = false
}
```

In this example from the docs, if I wanted to require that at least one file was supplied, I think I should be able to write:

```swift
struct Example: ParsableCommand {
    @Argument var files: [String]
    @Option var count: Int?
    @Option var index = 0
    @Flag var verbose = false
    @Flag var stripWhitespace = false
}
```

**Comment by rauhul** [comment]
(Disclaimer: I'm not in the office this week nor have access to a laptop) 

I believe your example _should_ work as you described and if it doesn't this is a bug. 

Could you attach the swift/argument-parser versions as well as the actual vs expected CLI output?

I will try to take a look asap when I return from break 😃

**Comment by dabrahams** [comment]
Not in a position to check right now, but it may be that this just fails when using a transform on the elements

**Comment by rauhul** [comment]
FWIW the two snippets above prepended with the following snippet work as expected:
```swift
import ArgumentParser

@main
extension Example { 
    func run() throws { print(self) }
}
```

Swift: 5.9
ArgumentParser: 1.2.2 (fee6933f37fde9a5e12a1e4aeaa93fe60116ff2a)

**Comment by dabrahams** [comment]
Thanks for checking it out.  I'm sorry if this report wasted your time; I filed it from a memory of something that hadn't worked out, without a reproducer.
