### ISSUE TITLE
Unable to compile as standalone package

### ISSUE THREAD

**Issue by Lantua** [apple/swift-argument-parser#57]
When I tried to compile a clean git-clone, I hit an error

```
Invalid redeclaration of `options`,
```

with the pointer to declarations being blank.

I traced it down to `Tests/PackageManagerTests/PackageManager/Clean.swift`. If I change the name of `options` to other names, the error message follows.

This is probably a compiler bug rather than the package bug, but maybe we should also find a workaround.

Note that it works fine as part of other packages.

Note: Xcode Version 11.3.1 (11C504)

**Comment by Lantua** [comment]
A workaround:

1. Move content of `PackageManagerTests/PackageManager/Clean.swift` to `PackageManagerTests/Tests.swift`.
2. Compile the package (which should be successful).
3. Move the content back.

**Comment by natecook1000** [comment]
Could you try reproducing this in Swift 5.2? I think there were some bugs fixed around synthesized conformances in nested types. Either using Xcode 11.4 or one of the recent snapshots from swift.org should be fine. Thanks!

**Comment by Lantua** [comment]
Confirmed that Swift 5.2 toolchain compiles successfully.

Setup:
- Xcode 11.3.1 (11C504)
- Swift 5.2 Snapshot 2020-03-05 (a) Toolchain
