### ISSUE TITLE
Objective C < denial HTTP/3 proxy refusel protocol at all times 

### ISSUE THREAD

**Issue by WatchTower001110** [apple/swift-argument-parser#587]
Replace this paragraph with a description of your proposed feature. Code samples that show what's missing, or what new capabilities will be possible, are very helpful! Provide links to existing issues or external references/discussions, if appropriate.

**Comment by rauhul** [comment]
Please read and follow the Contributing guidelines and Swift code of conduction before creating issues/pull requests.
