### ISSUE TITLE
Repeated flag causes error in some cases

### ISSUE THREAD

**Issue by glessard** [apple/swift-argument-parser#59]
When repeating a flag defined from a mutually-exclusive set, one gets an error.
```
enum Enum: String, CaseIterable { case s, t, u }

struct Options: Parsable Command {
  @Flag(name: .short, exclusivity: .exclusive, help: "Help!")
  var flag: Enum
}

let options = Options.parseOrExit()
```
```
$ options -s -s
Error: Value to be set with flag '-s' had already been set with flag '-s'
Usage: options -s -t -u
```

Should repetition in such a case simply be ignored?

**Comment by natecook1000** [comment]
Allowing it sounds like the right behavior to me — can you think of circumstances where it would be semantically important for the command to fail instead?

**Comment by glessard** [comment]
No, I can't think of such circumstances. Logic seems to dictate there shouldn't be, either...
