### ISSUE TITLE
Exclusivity isn't adjustable for Boolean flags with flag inversion settings

### ISSUE THREAD

**Issue by glessard** [apple/swift-argument-parser#60]
```
struct Options: ParsableCommand {
  @Flag(inversion: .prefixedNo)
  var x: Bool
}
options = Options.parseOrExit()
print(options.x)
```

```
$ options --x --no-x
false
$ options --no-x --x
true
```

Implicitly, they behave as if one had passed `FlagExclusivity.chooseLast`, but this is not adjustable.

**Comment by natecook1000** [comment]
Sounds like we could add that parameter with `.chooseLast` as the default.

**Comment by glessard** [comment]
Should it be an associated value on the FlagInversion cases? It only makes sense to have when there is a FlagInversion to begin with. (It might be too cute, though.)

**Comment by natecook1000** [comment]
No, this would need to be a new parameter to the Boolean `Flag` initializers that have an `inversion` parameter.
