### ISSUE TITLE
Ability to hide commands

### ISSUE THREAD

**Issue by dcantah** [apple/swift-argument-parser#642]
We can toggle the visibility of flags today, it would be nice if we could do the same with commands for folks who have hidden commands in their tools that are mostly for debug/development purposes.

**Comment by dickoff** [comment]
Doesn't this already exist with the `shouldDisplay` parameter of the `CommandConfiguration`? That will prevent it from showing up in the parent command's `--help` but it is still functional.
```
  ///   - shouldDisplay: A Boolean value indicating whether the command
  ///     should be shown in the extended help display.
  ```

**Comment by dcantah** [comment]
@dickoff Nope you're correct, I was grepping for `visibility` like what exists for flags before the transition from `shouldDisplay` 🤦

**Comment by rauhul** [comment]
Maybe we should replace this with visibility...

**Comment by dcantah** [comment]
Happy to re-open and re-target this at adding visibility in some new constructor if we want
