### ISSUE TITLE
`generate-manual` yields failedToRunSubprocess(error: Process returned non-zero exit code '5'.)

### ISSUE THREAD

**Issue by pepicrft** [apple/swift-argument-parser#653]
I'm trying to use the `generate-manual` plugin on [this repository](https://github.com/tuist/tuist), but get an error `failedToRunSubprocess(error: Process returned non-zero exit code '5'.)`. My hunch is that the plugin is trying to run a sub-process internally that's failing for some reason, and since the stderr of the process is not forwarded to the parent process, it's hard to tell what's causing the issue.

**ArgumentParser version:** `1.4.0`
**Swift version:**
```bash
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Clone [this repository](https://github.com/tuist/tuist) and run `swift package plugin generate-manual --configuration debug `.

### Expected behavior
I'd expect the command to succeed.

### Actual behavior
Failing command:

```
Building package in debug mode...
warning: 'path': /Users/pepicrft/src/github.com/tuist/tuist/.build/repositories/Path-7a19ec15 is not valid git repository for 'https://github.com/tuist/Path.git', will fetch again.
Fetching https://github.com/tuist/Path.git from cache
Fetched https://github.com/tuist/Path.git from cache (0.06s)
Built package in debug mode
Generating manual for tuistfixturegenerator...
Generated manual in '/Users/pepicrft/src/github.com/tuist/tuist/.build/plugins/GenerateManual/outputs/tuistfixturegenerator'
Generating manual for tuist...
Error: failedToRunSubprocess(error: Process returned non-zero exit code '5'.)
error: 'generate-manual' invocation failed: ''generate-manual' invocation failed with a nonzero exit code: '1'.'
```

**Comment by rauhul** [comment]
FWIW I added a print() and the underlying error is:
```
Optional("ArgumentParser/ParsableArguments.swift:283: Fatal error: Validation failed for `BenchmarkCommand`:\n\n- Multiple (3) `Option` or `Flag` arguments are named \"-f\".\n\n\n")
```
