### ISSUE TITLE
Avoid using throw in success scenarios for debugger-friendliness

### ISSUE THREAD

**Issue by tristanlabelle** [apple/swift-argument-parser#664]
This codebase relies on throwing error in success scenarios, which makes it painful to use in combination with enabling first-chance error in the debugger since one must continue past several breaks on errors. This is amplified by the fact that `swift-argument-parser` functionality is typically used before the application starts doing anything else.

![image](https://github.com/user-attachments/assets/ca3a72e6-b5ba-4660-b203-01c78635005d)

[`throw ValidationResult.success`](https://github.com/apple/swift-argument-parser/blob/44dd206a8528abde66dc52cd6e61f2991949b5a4/Sources/ArgumentParser/Parsable%20Types/ParsableArgumentsValidation.swift#L133:L140)

**Comment by florianpircher** [comment]
Duplicate of https://github.com/apple/swift-argument-parser/issues/274

But yes, this is a longstanding annoyance of this package.

**Comment by rauhul** [comment]
I think this is a fundamental issue with trying to validate against programmer misuse and using `Decodable` in the implementation of `ParsableArguments`. 

SAP is trying to make sure the user hasn't declared a custom CodingKeys which omits `@Argument` to do this it creates a "Validator" decoder which does some checking. The only way to early exit is to throw. 

See `ParsableArgumentsCodingKeyValidator`.

**Comment by rauhul** [comment]
Oh I just realized Nate said the same in the original bug.
