### ISSUE TITLE
clarify versioning rules (for 0.x releases)

### ISSUE THREAD

**Issue by weissi** [apple/swift-argument-parser#7]
I suppose `swift-argument-parser` uses SemVer once 1.0.0 has been tagged. Before that happens however, people will still start depending on `swift-argument-parser` because it got at least one tagged release (`0.0.1`). Therefore I think the project should clearly specify what its versioning rules are and probably offer a copy & pasteable recommended dependency line.

There could be a few different strategies:

- no guarantees at all (ie. folks should use `.exact(...)`) which I wouldn't recommend because that can easily lead to clashes. Of course, most libraries don't depend on argument parsers because that's something executables do but still...
- compatible API within one minor version but API additions allowed in patch releases. Ie. all `0.1.x` releases would be API stable (so 0.1.2 might add new API over 0.1.1 but isn't allowed to break it. 0.2.0 however is allowed to make breaking changes over 0.1.x) (`.upToNextMinor(...)`)
- normal SemVer rules (breaking changes only in majors) starting right at 0.0.1 (probably not desirable because I would imagine you don't want to lock all API right at the start?) (`from: "..."`)

**Comment by natecook1000** [comment]
Great question, @weissi — the second bullet is what we're going with until we reach 1.0.0. There's a note about this at the end of the README. Does that look like it addresses this concern, or should it be covered elsewhere?

**Comment by weissi** [comment]
@natecook1000 the README recommends:

    .package(url: "https://github.com/apple/swift-argument-parser", from: "0.0.1"),

which will pull all versions until 1.0.0. I see the comment that it's only API stable within the same minor version but I think the README should then also give a matching example using `upToNextMinor`, no?
