### ISSUE TITLE
Optional argument is listed as mandatory

### ISSUE THREAD

**Issue by fappelman** [apple/swift-argument-parser#76]
If an option has a default value **and** a transformation it is not listed as optional but as mandatory instead.

**ArgumentParser version:** `0.0.2`
**Swift version:** Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.3.0

### Checklist
- [X] I've reproduced the issue using the `master` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
```swift
import ArgumentParser
import Foundation

enum Mode {
    case mac
    case linux

    public static func mode(from: String) -> Mode? {
        switch from {
        case "mac":
            return .mac
        case "linux":
            return .linux
        default:
            return nil
        }
    }
}

struct Example: ParsableCommand {
    static let defaultMode: Mode = .mac
    static func toMode(_ string: String) throws -> Mode {
        Mode.mode(from: string)!
    }

    @Option(default: defaultMode, help: "Set mode, either linux or mac.", 
            transform: toMode)
    var mode: Mode
}

Example.main()
```

Produces output:

```log
USAGE: example --mode <mode>

OPTIONS:
  --mode <mode>           Set mode, either linux or mac. 
  -h, --help              Show help information.

Program ended with exit code: 0
```

### Expected behavior
I would expect the following USAGE line:

```log
USAGE: example [--mode <mode>]
```

### Actual behavior
I get:

```log
USAGE: example --mode <mode>
```

**Comment by griffin-stewie** [comment]
@fappelman This issue is fixed. :+1:
