### ISSUE TITLE
Make `URL` conforms to `ExpressibleByArgument`

### ISSUE THREAD

**Issue by YuAo** [apple/swift-argument-parser#82]
There are times a command line tool needs a local file URL or a remote URL as an argument.

For example `--build-path`, `--package-path` of the swift-package command. Of course one can use strings instead of URLs. But using URLs can benefit from validation, relative path handling, convenient path operations (like `appendingPathComponent`), etc.

A simple implementation would be something like

```
extension URL: ExpressibleByArgument {
  public init?(argument: String) {
    if let url = URL(string: argument), url.scheme != nil {
      self.init(string: argument)
    } else {
      // Assuming it is a file url.
      self.init(fileURLWithPath: argument)
    }
  }
}
```

`https://github.com` is parsed as a remote URL.
`.`, `folder`, `../`, `.build` are parsed as against current directory.
`file:///System`,  `file:///C:/Windows/` are parsed as file URL.

Things I'm not sure:
- ArgumentParser seems to use `@_implementationOnly import` for `Foundation`. This feature will break the `@_implementationOnly import` because it involves the `URL` type from `Foundation`. What's the story of the `@_implementationOnly import`?
- File paths on the Windows platform.

I've created a draft PR for this.

**Comment by natecook1000** [comment]
@YuAo — thanks for the issue and the pull request! At this time, we aren't exporting Foundation so that the parser can be used by tools that don't need or want to link the framework. To work around this, you can either use the inits that include the `transform` parameter or declare your own `ExpressibleByArgument` conformance.
