### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by rsalesas** [apple/swift-argument-parser#97]
I added the package to a new Swift Xcode project with rules of `0.0.3 to Major`, and on build I get an error of:

`Type of expression is ambiguous without more context`

in `parsePositionalValues` at this line:

`let extraValues: [(InputOrigin, String)] = argumentStack.map(\.0).map {`

**Comment by griffin-stewie** [comment]
@rsalesas I think you need to use Swift 5.2 toolchain.

**Comment by natecook1000** [comment]
@rsalesas Thanks for the report!

**Comment by natecook1000** [comment]
@rsalesas  This fix has been included in the new 0.0.4 release.
